# SPDX-License-Identifier: Apache-2.0
"""The screen socket protocol, version 1: its constants and message types.

Generated by scripts/gen_protocol.py from protocol/v1 -- do not edit.
"""

from __future__ import annotations

from typing import Final, Literal, TypedDict

PROTOCOL_VERSION: Final = 1
TAG_JPEG: Final = 1
TAG_H264: Final = 2
MESSAGE_MAX_BYTES: Final = 4096
TEXT_MAX_CHARS: Final = 2000
SCROLL_MAX_PT: Final = 600
TICKET_TTL_S: Final = 60
HELLO_TIMEOUT_S: Final = 10
CLOSE_BAD_GATEWAY: Final = 1014
CLOSE_BAD_MESSAGE: Final = 4400
CLOSE_UNAUTHORIZED: Final = 4401
CLOSE_FORBIDDEN: Final = 4403
CLOSE_UNSUPPORTED: Final = 4406
CLOSE_STOPPED: Final = 4410
CLOSE_RESTARTING: Final = 4412


# A finger going down, moving, lifting, or taken away without lifting.
TouchPhase = Literal[
    "down",
    "move",
    "up",
    "cancel",
]
TOUCH_PHASES: tuple[TouchPhase, ...] = (
    "down",
    "move",
    "up",
    "cancel",
)


# The hardware buttons a person may press from a viewer.
PanelButton = Literal[
    "home",
    "lock",
    "side",
    "siri",
]
PANEL_BUTTONS: tuple[PanelButton, ...] = (
    "home",
    "lock",
    "side",
    "siri",
)


# Keys that are not text. Text is sent whole, as a text input.
KeyName = Literal[
    "return",
    "escape",
    "delete",
    "tab",
    "space",
    "right",
    "left",
    "down",
    "up",
]
KEY_NAMES: tuple[KeyName, ...] = (
    "return",
    "escape",
    "delete",
    "tab",
    "space",
    "right",
    "left",
    "down",
    "up",
)


# The device's appearance.
Appearance = Literal[
    "light",
    "dark",
]
APPEARANCES: tuple[Appearance, ...] = (
    "light",
    "dark",
)


# Something a connector can do with a device. The viewer and the agent tools offer only what the connector in use
# can do.
Capability = Literal[
    "lifecycle",
    "device_list",
    "appearance",
    "open_url",
    "app_install",
    "app_launch",
    "logs",
    "screenshot",
    "stream_jpeg",
    "stream_h264",
    "input_touch",
    "input_button",
    "input_key",
    "input_text",
    "element_tree",
    "build_preview",
]
CAPABILITIES: tuple[Capability, ...] = (
    "lifecycle",
    "device_list",
    "appearance",
    "open_url",
    "app_install",
    "app_launch",
    "logs",
    "screenshot",
    "stream_jpeg",
    "stream_h264",
    "input_touch",
    "input_button",
    "input_key",
    "input_text",
    "element_tree",
    "build_preview",
)


# How screen frames travel: JPEG images, or an H.264 Annex-B stream.
Encoding = Literal[
    "jpeg",
    "h264",
]
ENCODINGS: tuple[Encoding, ...] = (
    "jpeg",
    "h264",
)


# The encoding a scope asks for. auto is H.264 where the viewer can decode it, JPEG where it cannot.
EncodingSetting = Literal[
    "auto",
    "jpeg",
    "h264",
]
ENCODING_SETTINGS: tuple[EncodingSetting, ...] = (
    "auto",
    "jpeg",
    "h264",
)


# How a device stands: being brought up, streaming and taking input, running but failing to stream, unable to start,
# or gone.
DeviceState = Literal[
    "booting",
    "ready",
    "stalled",
    "failed",
    "stopped",
]
DEVICE_STATES: tuple[DeviceState, ...] = (
    "booting",
    "ready",
    "stalled",
    "failed",
    "stopped",
)


#: A fraction of the screen: 0 at its left or top edge, 1 at its right or bottom edge.
Share = float


#: A point on the screen as fractions of its width and height.
Point = tuple[Share, Share]


class Gesture(TypedDict):
    """The gesture an intent announces.
    """
    #: What it is: tap, long_press, swipe, drag, type, press, look, app or build. A viewer draws kinds it does not
    #: know as a caption.
    kind: str
    duration_ms: int
    #: Where it lands, in order; empty for a gesture with no place on the screen.
    points: list[Point]


class AgentIntent(TypedDict):
    """A gesture about to land. While anyone watches, the server waits lead_ms after sending it, so the pointer
    arrives first.
    """
    type: Literal["agent"]
    id: str
    phase: Literal["intent"]
    agent: Agent
    #: False when the agent cursor is off: an agent is using the device, and nothing is drawn.
    pointer: bool
    #: The label of the element the gesture lands on, if it has one.
    label: str
    caption: str
    lead_ms: int
    gesture: Gesture


class AgentDone(TypedDict):
    """The gesture an intent announced is over.
    """
    type: Literal["agent"]
    id: str
    phase: Literal["done"]
    ok: bool


#: What an agent is about to do on the device, and whether it worked. A viewer draws the intent with its own
#: pointer.
AgentEvent = AgentIntent | AgentDone


class TouchInput(TypedDict):
    """One finger's touch. A down, its moves and its up are one gesture on the device.
    """
    type: Literal["touch"]
    phase: TouchPhase
    nx: Share
    ny: Share


class ScrollInput(TypedDict):
    """A scroll wheel's movement at a point.
    """
    type: Literal["scroll"]
    nx: Share
    ny: Share
    #: How far the content moves, in points; positive scrolls down. The server clamps it to scroll_max_pt either
    #: way.
    dy: float


class ButtonInput(TypedDict):
    type: Literal["button"]
    name: PanelButton


class KeyInput(TypedDict):
    type: Literal["key"]
    name: KeyName


class TextInput(TypedDict):
    """Text for the focused field. It is put on the device's pasteboard and pasted, whatever the Mac's keyboard
    layout.
    """
    type: Literal["text"]
    text: str


class AppearanceInput(TypedDict):
    type: Literal["appearance"]
    mode: Appearance


#: What a person does to the screen, sent by the viewer after the hello. The server acts on these and nothing else,
#: and ignores any other message.
ClientInput = TouchInput | ScrollInput | ButtonInput | KeyInput | TextInput | AppearanceInput


class Size(TypedDict):
    """A width and a height.
    """
    w: int
    h: int


class Screen(TypedDict):
    """A device's screen: in points, which touches and snapshots use, and in pixels, which frames use.
    """
    points: Size
    pixels: Size
    scale: float


class Device(TypedDict):
    """A running device, as a viewer is told about it.
    """
    #: The simulator's device identifier.
    udid: str
    name: str
    #: The runtime as a person says it, such as iOS 26.5.
    runtime: str
    state: DeviceState
    #: Why the device is stalled, failed or stopped; null otherwise.
    reason: str | None
    #: How long the device has been in this state.
    since_ms: int
    #: How many screen sockets watch the device.
    viewers: int
    #: What the device is kept for while agents' gestures would get in its way, such as a test run; null otherwise.
    busy: str | None
    #: Whether SimMirror created this device.
    created: bool
    #: Whether SimMirror booted this device, and so may shut it down.
    booted_by_us: bool
    screen: Screen | None


class Agent(TypedDict):
    """Who is acting on a device: an agent, by a key that stays the same for its connection, and the title a viewer
    shows.
    """
    key: str
    title: str


class ServerHello(TypedDict):
    """What the server offers, sent as soon as the socket is admitted.
    """
    type: Literal["hello"]
    v: Literal[1]
    #: The server's name and version, such as sim-mirror/0.1.0.
    server: str
    encodings: list[Encoding]
    #: The connector driving the device, such as idb or simctl.
    connector: str
    capabilities: list[Capability]
    #: Why a connector other than the one asked for is in use; null otherwise.
    fallback_reason: str | None


class ClientHello(TypedDict):
    """The client's answer: the encodings it decodes, most preferred first. A server ignores encodings it does not
    know.
    """
    type: Literal["hello"]
    v: Literal[1]
    encodings: list[Encoding]


#: The first message each way on a screen socket: the server says what it offers, and the client answers with the
#: encodings it decodes, most preferred first.
Hello = ServerHello | ClientHello


class ScopeStatusStream(TypedDict):
    encoding: EncodingSetting
    fps: int


class ScopeStatusCursor(TypedDict):
    enabled: bool
    lead_ms: int


class ScopeStatus(TypedDict):
    """Whether a scope can have a simulator, why not, how its device stands, and what the viewer is offered. The HTTP
    status route answers with it.
    """
    enabled: bool
    #: Why the scope cannot have a simulator now; null when it can.
    reason: str | None
    device: Device | None
    stream: ScopeStatusStream
    cursor: ScopeStatusCursor
    #: The connector that drives devices for this scope; null when none is available.
    connector: str | None
    capabilities: list[Capability]
    #: Why a connector other than the one asked for is in use; null otherwise.
    fallback_reason: str | None


class Started(ScopeStatus):
    """A scope's status once its device is being brought up, with a one-shot ticket for its screen socket.
    """
    ticket: str


class DeviceChoice(TypedDict):
    """A simulator on this Mac a scope could use, for a device picker.
    """
    udid: str
    name: str
    runtime: str
    #: What simctl says, such as Booted or Shutdown.
    state: str
    created: bool


class StatusEvent(Device):
    """How the device stands: sent on the screen socket after the stream starts, and whenever that changes.
    """
    type: Literal["status"]


class StreamStart(TypedDict):
    """The encoding the server chose from the client's hello. Binary frames in that encoding follow.
    """
    type: Literal["stream"]
    encoding: Encoding
