# SPDX-License-Identifier: Apache-2.0
"""The screen socket protocol, version 1: its constants and message types.

Generated by scripts/gen_protocol.py from protocol/v1 -- do not edit.
"""

from __future__ import annotations

from typing import Any, Final, Literal, TypedDict

PROTOCOL_VERSION: Final = 1
TAG_JPEG: Final = 1
TAG_H264: Final = 2
MESSAGE_MAX_BYTES: Final = 4096
TEXT_MAX_CHARS: Final = 2000
SCROLL_MAX_PT: Final = 600
TICKET_TTL_S: Final = 60
HELLO_TIMEOUT_S: Final = 10
WORKING_EVERY_S: Final = 10
SCREEN_TEXT_MAX_BOXES: Final = 200
CLOSE_BAD_GATEWAY: Final = 1014
CLOSE_BAD_MESSAGE: Final = 4400
CLOSE_UNAUTHORIZED: Final = 4401
CLOSE_FORBIDDEN: Final = 4403
CLOSE_UNSUPPORTED: Final = 4406
CLOSE_STOPPED: Final = 4410
CLOSE_RESTARTING: Final = 4412


# A finger going down, moving, lifting, or taken away without lifting.
TouchPhase = Literal[
    "down",
    "move",
    "up",
    "cancel",
]
TOUCH_PHASES: tuple[TouchPhase, ...] = (
    "down",
    "move",
    "up",
    "cancel",
)


# The hardware buttons a person may press from a viewer.
PanelButton = Literal[
    "home",
    "lock",
    "side",
    "siri",
]
PANEL_BUTTONS: tuple[PanelButton, ...] = (
    "home",
    "lock",
    "side",
    "siri",
)


# Keys that are not text. Text is sent whole, as a text input.
KeyName = Literal[
    "return",
    "escape",
    "delete",
    "tab",
    "space",
    "right",
    "left",
    "down",
    "up",
]
KEY_NAMES: tuple[KeyName, ...] = (
    "return",
    "escape",
    "delete",
    "tab",
    "space",
    "right",
    "left",
    "down",
    "up",
)


# The device's appearance.
Appearance = Literal[
    "light",
    "dark",
]
APPEARANCES: tuple[Appearance, ...] = (
    "light",
    "dark",
)


# Something a connector can do with a device. The viewer and the agent tools offer only what the connector in use
# can do.
Capability = Literal[
    "lifecycle",
    "device_list",
    "appearance",
    "open_url",
    "app_install",
    "app_launch",
    "logs",
    "screenshot",
    "stream_jpeg",
    "stream_h264",
    "input_touch",
    "input_button",
    "input_key",
    "input_text",
    "element_tree",
    "build_preview",
]
CAPABILITIES: tuple[Capability, ...] = (
    "lifecycle",
    "device_list",
    "appearance",
    "open_url",
    "app_install",
    "app_launch",
    "logs",
    "screenshot",
    "stream_jpeg",
    "stream_h264",
    "input_touch",
    "input_button",
    "input_key",
    "input_text",
    "element_tree",
    "build_preview",
)


# How screen frames travel: JPEG images, or an H.264 Annex-B stream.
Encoding = Literal[
    "jpeg",
    "h264",
]
ENCODINGS: tuple[Encoding, ...] = (
    "jpeg",
    "h264",
)


# The encoding a scope asks for. auto is H.264 where the viewer can decode it, JPEG where it cannot.
EncodingSetting = Literal[
    "auto",
    "jpeg",
    "h264",
]
ENCODING_SETTINGS: tuple[EncodingSetting, ...] = (
    "auto",
    "jpeg",
    "h264",
)


# How a device stands: being brought up, streaming and taking input, running but failing to stream, unable to start,
# or gone.
DeviceState = Literal[
    "booting",
    "ready",
    "stalled",
    "failed",
    "stopped",
]
DEVICE_STATES: tuple[DeviceState, ...] = (
    "booting",
    "ready",
    "stalled",
    "failed",
    "stopped",
)


# What a token is for: an agent's tools, a person's viewer, a host's namespaces, or everything.
TokenKind = Literal[
    "agent",
    "viewer",
    "admin",
    "host",
]
TOKEN_KINDS: tuple[TokenKind, ...] = (
    "agent",
    "viewer",
    "admin",
    "host",
)


# What a spent login code or embed ticket opens: a viewer, a framed viewer, or a viewer that may change settings.
SessionKind = Literal[
    "viewer",
    "embed",
    "settings",
]
SESSION_KINDS: tuple[SessionKind, ...] = (
    "viewer",
    "embed",
    "settings",
)


# When a change takes effect: at once, on a viewer's next connection, on the device next brought up, or when the
# daemon restarts.
SettingEffect = Literal[
    "live",
    "next_connection",
    "next_device",
    "restart",
]
SETTING_EFFECTS: tuple[SettingEffect, ...] = (
    "live",
    "next_connection",
    "next_device",
    "restart",
)


# Whom a setting is for: each scope, or only the whole daemon.
SettingReach = Literal[
    "scope",
    "global",
]
SETTING_REACHES: tuple[SettingReach, ...] = (
    "scope",
    "global",
)


# Where a value comes from, lowest first: the default, config.toml, the scope's table in it, a SIM_MIRROR_*
# variable, or the command line.
SettingLayer = Literal[
    "default",
    "file",
    "scope",
    "environment",
    "command_line",
]
SETTING_LAYERS: tuple[SettingLayer, ...] = (
    "default",
    "file",
    "scope",
    "environment",
    "command_line",
)


# What the asker may do: read only, change what is not sensitive, or change everything.
SettingsAccess = Literal[
    "read",
    "write",
    "write_sensitive",
]
SETTINGS_ACCESS: tuple[SettingsAccess, ...] = (
    "read",
    "write",
    "write_sensitive",
)


# Whether a change is for this scope alone or for every scope.
SettingsTarget = Literal[
    "scope",
    "all",
]
SETTINGS_TARGETS: tuple[SettingsTarget, ...] = (
    "scope",
    "all",
)


#: A fraction of the screen: 0 at its left or top edge, 1 at its right or bottom edge.
Share = float


#: A point on the screen as fractions of its width and height.
Point = tuple[Share, Share]


class Gesture(TypedDict):
    """The gesture an intent announces.
    """
    #: What it is: tap, long_press, swipe, drag, type, press, look, app or build. A viewer draws kinds it does not
    #: know as a caption.
    kind: str
    duration_ms: int
    #: Where it lands, in order; empty for a gesture with no place on the screen.
    points: list[Point]


class AgentIntent(TypedDict):
    """A gesture about to land. While anyone watches, the server waits lead_ms after sending it, so the pointer
    arrives first.
    """
    type: Literal["agent"]
    id: str
    phase: Literal["intent"]
    agent: Agent
    #: False when the agent cursor is off: an agent is using the device, and nothing is drawn.
    pointer: bool
    #: The label of the element the gesture lands on, if it has one.
    label: str
    caption: str
    lead_ms: int
    #: How long the pointer stays, resting where it last acted, after the agent's last event. 0: only while the
    #: gesture is drawn.
    linger_ms: int
    gesture: Gesture


class AgentDone(TypedDict):
    """The gesture an intent announced is over.
    """
    type: Literal["agent"]
    id: str
    phase: Literal["done"]
    ok: bool


class AgentWorking(TypedDict):
    """An agent is still at work on the device -- a tool call has started, is running, or has just ended -- with
    nothing new to draw. Sent when a call starts and ends, and every WORKING_EVERY_S while a long one, such as a
    build or a test run, goes on.
    """
    type: Literal["agent"]
    id: str
    phase: Literal["working"]
    agent: Agent
    #: True while the call runs, when another of these follows within WORKING_EVERY_S; false once it has ended.
    ongoing: bool
    linger_ms: int


#: What an agent is about to do on the device, whether it worked, and that it is still working. A viewer draws the
#: intent with its own pointer, and keeps it while the agent works.
AgentEvent = AgentIntent | AgentDone | AgentWorking


class TouchInput(TypedDict):
    """One finger's touch. A down, its moves and its up are one gesture on the device.
    """
    type: Literal["touch"]
    phase: TouchPhase
    nx: Share
    ny: Share


class ScrollInput(TypedDict):
    """A scroll wheel's movement at a point.
    """
    type: Literal["scroll"]
    nx: Share
    ny: Share
    #: How far the content moves, in points; positive scrolls down. The server clamps it to scroll_max_pt either
    #: way.
    dy: float


class ButtonInput(TypedDict):
    type: Literal["button"]
    name: PanelButton


class KeyInput(TypedDict):
    type: Literal["key"]
    name: KeyName


class TextInput(TypedDict):
    """Text for the focused field. It is typed as key presses, or put on the device's pasteboard and pasted, as the
    scope's device.typing setting says.
    """
    type: Literal["text"]
    text: str


class AppearanceInput(TypedDict):
    type: Literal["appearance"]
    mode: Appearance


#: What a person does to the screen, sent by the viewer after the hello. The server acts on these and nothing else,
#: and ignores any other message.
ClientInput = TouchInput | ScrollInput | ButtonInput | KeyInput | TextInput | AppearanceInput


class Size(TypedDict):
    """A width and a height.
    """
    w: int
    h: int


class Screen(TypedDict):
    """A device's screen: in points, which touches and snapshots use, and in pixels, which frames use.
    """
    points: Size
    pixels: Size
    scale: float


class Device(TypedDict):
    """A running device, as a viewer is told about it.
    """
    #: The simulator's device identifier.
    udid: str
    name: str
    #: The runtime as a person says it, such as iOS 26.5.
    runtime: str
    state: DeviceState
    #: Why the device is stalled, failed or stopped; null otherwise.
    reason: str | None
    #: How long the device has been in this state.
    since_ms: int
    #: How many screen sockets watch the device.
    viewers: int
    #: What the device is kept for while agents' gestures would get in its way, such as a test run; null otherwise.
    busy: str | None
    #: Whether SimMirror created this device.
    created: bool
    #: Whether SimMirror booted this device, and so may shut it down.
    booted_by_us: bool
    screen: Screen | None


class Agent(TypedDict):
    """Who is acting on a device: an agent, by a key that stays the same for its connection, and the title a viewer
    shows.
    """
    key: str
    title: str


class ServerHello(TypedDict):
    """What the server offers, sent as soon as the socket is admitted.
    """
    type: Literal["hello"]
    v: Literal[1]
    #: The server's name and version, such as sim-mirror/0.1.0.
    server: str
    encodings: list[Encoding]
    #: The connector driving the device, such as idb or simctl.
    connector: str
    capabilities: list[Capability]
    #: Why a connector other than the one asked for is in use; null otherwise.
    fallback_reason: str | None


class ClientHello(TypedDict):
    """The client's answer: the encodings it decodes, most preferred first. A server ignores encodings it does not
    know.
    """
    type: Literal["hello"]
    v: Literal[1]
    encodings: list[Encoding]


#: The first message each way on a screen socket: the server says what it offers, and the client answers with the
#: encodings it decodes, most preferred first.
Hello = ServerHello | ClientHello


class Refusal(TypedDict):
    """Why a request was refused, with its HTTP status. A body that is not the right shape has a list of what is
    wrong with it instead of one sentence.
    """
    detail: str | list[RefusalProblem]


class RefusalProblem(TypedDict):
    """One thing wrong with a request's body.
    """
    msg: str


class Health(TypedDict):
    """GET /healthz: that the daemon is up. Given a nonce, proof that it holds the admin token; given a token's id
    too, proof that it knows that token.
    """
    server: str
    protocol: int
    port: int
    #: HMAC-SHA256 of the nonce, keyed by the admin token; null when no nonce was given.
    proof: str | None
    #: HMAC-SHA256 of the nonce, keyed by the hex SHA-256 of the named token; null when no nonce or no known token
    #: id was given.
    token_proof: str | None


class Stopped(TypedDict):
    """DELETE on a scope: whether its device was running and has been let go.
    """
    stopped: bool


class DeviceList(TypedDict):
    """GET a scope's devices: the simulators it could use, for a picker.
    """
    devices: list[DeviceChoice]


class Chosen(TypedDict):
    """PUT a scope's device: the simulator it uses from now on.
    """
    udid: str


class EmbedTicket(TypedDict):
    """POST a scope's embed tickets: the path a page frames, with a one-shot ticket in its fragment, and how long the
    ticket lasts.
    """
    url: str
    expires_in_s: float


class Exchanged(TypedDict):
    """POST /api/v1/auth/exchange: a viewer token for the scope a login code or embed ticket was for.
    """
    token: str
    scope: str
    kind: SessionKind
    expires_in_s: float


class Lease(TypedDict):
    """POST an agent's lease: its scope's device is not stopped as idle for this long.
    """
    scope: str
    expires_in_s: float


class TokenRecord(TypedDict):
    """A token as it may be shown: never the token itself, nor its digest.
    """
    id: str
    kind: TokenKind
    #: Scope ids, `name:*` for a namespace, or `*` for every scope.
    scopes: list[str]
    label: str
    #: The folders its agents may reach.
    roots: list[str]
    #: When it was made, in seconds since the epoch.
    created: float
    #: The id of the host token that made it; empty when the admin did.
    host: str


class MadeToken(TokenRecord):
    """A token just made: its record, and the token itself, which is never shown again.
    """
    token: str


class TokenList(TypedDict):
    """GET the tokens a host made.
    """
    tokens: list[TokenRecord]


class Revoked(TypedDict):
    """DELETE a token: whether there was one to revoke.
    """
    revoked: bool


class AgentTool(TypedDict):
    """A tool as an MCP manifest lists it.
    """
    name: str
    description: str
    #: A JSON Schema of its arguments.
    inputSchema: dict[str, Any]


class AgentManifest(TypedDict):
    """GET /api/v1/agent/manifest, not wrapped in an Answer: the tools an agent is offered and how to use them -- or
    none, and why, in instructions.
    """
    tools: list[AgentTool]
    instructions: str


class TextContent(TypedDict):
    """Text in a tool result.
    """
    type: Literal["text"]
    text: str


class ImageContent(TypedDict):
    """An image in a tool result, base64-encoded.
    """
    type: Literal["image"]
    data: str
    mimeType: str


class ToolResult(TypedDict):
    """POST /api/v1/agent/call, not wrapped in an Answer: an MCP tool result. A refused or failed call is a result
    with isError, not an HTTP error.
    """
    content: list[TextContent | ImageContent]
    isError: bool


class TextBox(TypedDict):
    """A line of text read from the screen's pixels, and the box around it as shares of the screen.
    """
    text: str
    #: How sure the reading is of the text.
    confidence: float
    x: Share
    y: Share
    w: Share
    h: Share


class ScreenText(TypedDict):
    """The text a reading of the screen's pixels found, and where, while the scope's perception.ocr_overlay is on.
    Each replaces the last; one with no boxes clears them, sent when the screen is about to change or the overlay
    is turned off. A viewer draws the boxes over the screen, never into it.
    """
    type: Literal["screen_text"]
    id: str
    #: The longest a viewer keeps the boxes, unless another ScreenText comes first. 0: until one does.
    hold_ms: int
    #: In the order the text reads; empty to clear. At most SCREEN_TEXT_MAX_BOXES.
    boxes: list[TextBox]


class FlagRule(TypedDict):
    """true or false.
    """
    kind: Literal["flag"]


class WholeRule(TypedDict):
    """A whole number from low to high.
    """
    kind: Literal["whole"]
    low: int
    high: int


class ChoiceRule(TypedDict):
    """One of the options.
    """
    kind: Literal["choice"]
    options: list[str]


class TextRule(TypedDict):
    """One line of text: a name, a path, a build configuration or a connector's name.
    """
    kind: Literal["text"]
    format: str
    max_length: int
    required: bool
    example: str
    #: Values worth offering to pick from, such as the connectors installed; any other the rule allows may still be
    #: typed.
    suggestions: list[str] | None


class OriginsRule(TypedDict):
    """A list of web origins, such as http://localhost:3000.
    """
    kind: Literal["origins"]
    max_items: int


#: What a setting's value may be, told apart by kind.
RuleSpec = FlagRule | WholeRule | ChoiceRule | TextRule | OriginsRule


#: A setting's value: a flag, a whole number, text, or a list of text.
SettingValue = bool | int | str | list[str]


class SettingOrigin(TypedDict):
    layer: SettingLayer
    #: What in the layer set it: the file, the scope's table, or the variable.
    detail: str | None


class SettingsSection(TypedDict):
    """A tab of the panel: a top-level table of config.toml.
    """
    #: The table's name; empty for the top of the file.
    id: str
    title: str
    doc: str


class SettingEntry(TypedDict):
    #: Where it lives in config.toml, such as stream.fps.
    path: str
    section: str
    doc: str
    rule: RuleSpec
    value: SettingValue
    default: SettingValue
    origin: SettingOrigin
    effect: SettingEffect
    reach: SettingReach
    #: It decides what SimMirror runs or who may reach it: a page changes it only once a person confirms at the
    #: terminal.
    sensitive: bool
    #: Why it cannot be changed here -- such as a variable setting it -- or null when it can.
    locked: str | None
    #: How to change it at the terminal instead.
    command: str


class SettingsView(TypedDict):
    """Every setting as a scope sees it, grouped into sections, and what the asker may do with them.
    """
    scope: str
    access: SettingsAccess
    #: What the asker should know before changing anything -- such as how to open settings that may be changed -- or
    #: null.
    notice: str | None
    sections: list[SettingsSection]
    settings: list[SettingEntry]


class SettingValueChange(TypedDict):
    path: str
    value: SettingValue


class SettingsChange(TypedDict):
    """Values to set and settings to put back to what the layer below says, all or none.
    """
    target: SettingsTarget
    set: list[SettingValueChange]
    unset: list[str]
    #: The code `sim-mirror settings confirm` printed, for a change that includes a sensitive setting.
    confirmation: str | None


class SettingsProblem(TypedDict):
    path: str
    message: str


class PendingConfirmation(TypedDict):
    """A sensitive change waiting for a person to confirm it at the terminal.
    """
    id: str
    #: What the change does, as the terminal shows it.
    summary: str
    #: The command that shows the change and its code.
    command: str
    expires_in_s: float


class SettingsRefusal(TypedDict):
    """A change refused, with each setting's problem, or the confirmation it waits for.
    """
    detail: str
    errors: list[SettingsProblem]
    confirmation: PendingConfirmation | None


class ScopeStatusStream(TypedDict):
    encoding: EncodingSetting
    fps: int


class ScopeStatusCursor(TypedDict):
    enabled: bool
    lead_ms: int


class ScopeStatus(TypedDict):
    """Whether a scope can have a simulator, why not, how its device stands, and what the viewer is offered. The HTTP
    status route answers with it.
    """
    enabled: bool
    #: Why the scope cannot have a simulator now; null when it can.
    reason: str | None
    device: Device | None
    stream: ScopeStatusStream
    cursor: ScopeStatusCursor
    #: The connector that drives devices for this scope; null when none is available.
    connector: str | None
    capabilities: list[Capability]
    #: Why a connector other than the one asked for is in use; null otherwise.
    fallback_reason: str | None


class Started(ScopeStatus):
    """A scope's status once its device is being brought up, with a one-shot ticket for its screen socket.
    """
    ticket: str


class DeviceChoice(TypedDict):
    """A simulator on this Mac a scope could use, for a device picker.
    """
    udid: str
    name: str
    runtime: str
    #: What simctl says, such as Booted or Shutdown.
    state: str
    created: bool


class StatusEvent(Device):
    """How the device stands: sent on the screen socket after the stream starts, and whenever that changes.
    """
    type: Literal["status"]


class StreamStart(TypedDict):
    """The encoding the server chose from the client's hello. Binary frames in that encoding follow.
    """
    type: Literal["stream"]
    encoding: Encoding
