// SPDX-License-Identifier: Apache-2.0
// The screen socket protocol, version 1: its constants and message types.
// Generated by scripts/gen_protocol.py from protocol/v1 -- do not edit.

export const PROTOCOL_VERSION = 1
export const TAG_JPEG = 1
export const TAG_H264 = 2
export const MESSAGE_MAX_BYTES = 4096
export const TEXT_MAX_CHARS = 2000
export const SCROLL_MAX_PT = 600
export const TICKET_TTL_S = 60
export const HELLO_TIMEOUT_S = 10
export const CLOSE_BAD_GATEWAY = 1014
export const CLOSE_BAD_MESSAGE = 4400
export const CLOSE_UNAUTHORIZED = 4401
export const CLOSE_FORBIDDEN = 4403
export const CLOSE_UNSUPPORTED = 4406
export const CLOSE_STOPPED = 4410
export const CLOSE_RESTARTING = 4412

// A finger going down, moving, lifting, or taken away without lifting.
export const TOUCH_PHASES = ['down', 'move', 'up', 'cancel'] as const
export type TouchPhase = (typeof TOUCH_PHASES)[number]

// The hardware buttons a person may press from a viewer.
export const PANEL_BUTTONS = ['home', 'lock', 'side', 'siri'] as const
export type PanelButton = (typeof PANEL_BUTTONS)[number]

// Keys that are not text. Text is sent whole, as a text input.
export const KEY_NAMES = ['return', 'escape', 'delete', 'tab', 'space', 'right', 'left', 'down', 'up'] as const
export type KeyName = (typeof KEY_NAMES)[number]

// The device's appearance.
export const APPEARANCES = ['light', 'dark'] as const
export type Appearance = (typeof APPEARANCES)[number]

// Something a connector can do with a device. The viewer and the agent tools offer only what the connector in use
// can do.
export const CAPABILITIES = ['lifecycle', 'device_list', 'appearance', 'open_url', 'app_install', 'app_launch', 'logs', 'screenshot', 'stream_jpeg', 'stream_h264', 'input_touch', 'input_button', 'input_key', 'input_text', 'element_tree', 'build_preview'] as const
export type Capability = (typeof CAPABILITIES)[number]

// How screen frames travel: JPEG images, or an H.264 Annex-B stream.
export const ENCODINGS = ['jpeg', 'h264'] as const
export type Encoding = (typeof ENCODINGS)[number]

// The encoding a scope asks for. auto is H.264 where the viewer can decode it, JPEG where it cannot.
export const ENCODING_SETTINGS = ['auto', 'jpeg', 'h264'] as const
export type EncodingSetting = (typeof ENCODING_SETTINGS)[number]

// How a device stands: being brought up, streaming and taking input, running but failing to stream, unable to
// start, or gone.
export const DEVICE_STATES = ['booting', 'ready', 'stalled', 'failed', 'stopped'] as const
export type DeviceState = (typeof DEVICE_STATES)[number]

// When a change takes effect: at once, on a viewer's next connection, on the device next brought up, or when the
// daemon restarts.
export const SETTING_EFFECTS = ['live', 'next_connection', 'next_device', 'restart'] as const
export type SettingEffect = (typeof SETTING_EFFECTS)[number]

// Whom a setting is for: each scope, or only the whole daemon.
export const SETTING_REACHES = ['scope', 'global'] as const
export type SettingReach = (typeof SETTING_REACHES)[number]

// Where a value comes from, lowest first: the default, config.toml, the scope's table in it, a SIM_MIRROR_*
// variable, or the command line.
export const SETTING_LAYERS = ['default', 'file', 'scope', 'environment', 'command_line'] as const
export type SettingLayer = (typeof SETTING_LAYERS)[number]

// What the asker may do: read only, change what is not sensitive, or change everything.
export const SETTINGS_ACCESS = ['read', 'write', 'write_sensitive'] as const
export type SettingsAccess = (typeof SETTINGS_ACCESS)[number]

// Whether a change is for this scope alone or for every scope.
export const SETTINGS_TARGETS = ['scope', 'all'] as const
export type SettingsTarget = (typeof SETTINGS_TARGETS)[number]

// A fraction of the screen: 0 at its left or top edge, 1 at its right or bottom edge.
export type Share = number

// A point on the screen as fractions of its width and height.
export type Point = [Share, Share]

// The gesture an intent announces.
export interface Gesture {
  // What it is: tap, long_press, swipe, drag, type, press, look, app or build. A viewer draws kinds it does not
  // know as a caption.
  kind: string
  duration_ms: number
  // Where it lands, in order; empty for a gesture with no place on the screen.
  points: Point[]
}

// A gesture about to land. While anyone watches, the server waits lead_ms after sending it, so the pointer arrives
// first.
export interface AgentIntent {
  type: 'agent'
  id: string
  phase: 'intent'
  agent: Agent
  // False when the agent cursor is off: an agent is using the device, and nothing is drawn.
  pointer: boolean
  // The label of the element the gesture lands on, if it has one.
  label: string
  caption: string
  lead_ms: number
  gesture: Gesture
}

// The gesture an intent announced is over.
export interface AgentDone {
  type: 'agent'
  id: string
  phase: 'done'
  ok: boolean
}

// What an agent is about to do on the device, and whether it worked. A viewer draws the intent with its own
// pointer.
export type AgentEvent = AgentIntent | AgentDone

// One finger's touch. A down, its moves and its up are one gesture on the device.
export interface TouchInput {
  type: 'touch'
  phase: TouchPhase
  nx: Share
  ny: Share
}

// A scroll wheel's movement at a point.
export interface ScrollInput {
  type: 'scroll'
  nx: Share
  ny: Share
  // How far the content moves, in points; positive scrolls down. The server clamps it to scroll_max_pt either way.
  dy: number
}

export interface ButtonInput {
  type: 'button'
  name: PanelButton
}

export interface KeyInput {
  type: 'key'
  name: KeyName
}

// Text for the focused field. It is put on the device's pasteboard and pasted, whatever the Mac's keyboard layout.
export interface TextInput {
  type: 'text'
  text: string
}

export interface AppearanceInput {
  type: 'appearance'
  mode: Appearance
}

// What a person does to the screen, sent by the viewer after the hello. The server acts on these and nothing else,
// and ignores any other message.
export type ClientInput = TouchInput | ScrollInput | ButtonInput | KeyInput | TextInput | AppearanceInput

// A width and a height.
export interface Size {
  w: number
  h: number
}

// A device's screen: in points, which touches and snapshots use, and in pixels, which frames use.
export interface Screen {
  points: Size
  pixels: Size
  scale: number
}

// A running device, as a viewer is told about it.
export interface Device {
  // The simulator's device identifier.
  udid: string
  name: string
  // The runtime as a person says it, such as iOS 26.5.
  runtime: string
  state: DeviceState
  // Why the device is stalled, failed or stopped; null otherwise.
  reason: string | null
  // How long the device has been in this state.
  since_ms: number
  // How many screen sockets watch the device.
  viewers: number
  // What the device is kept for while agents' gestures would get in its way, such as a test run; null otherwise.
  busy: string | null
  // Whether SimMirror created this device.
  created: boolean
  // Whether SimMirror booted this device, and so may shut it down.
  booted_by_us: boolean
  screen: Screen | null
}

// Who is acting on a device: an agent, by a key that stays the same for its connection, and the title a viewer
// shows.
export interface Agent {
  key: string
  title: string
}

// What the server offers, sent as soon as the socket is admitted.
export interface ServerHello {
  type: 'hello'
  v: 1
  // The server's name and version, such as sim-mirror/0.1.0.
  server: string
  encodings: Encoding[]
  // The connector driving the device, such as idb or simctl.
  connector: string
  capabilities: Capability[]
  // Why a connector other than the one asked for is in use; null otherwise.
  fallback_reason: string | null
}

// The client's answer: the encodings it decodes, most preferred first. A server ignores encodings it does not know.
export interface ClientHello {
  type: 'hello'
  v: 1
  encodings: Encoding[]
}

// The first message each way on a screen socket: the server says what it offers, and the client answers with the
// encodings it decodes, most preferred first.
export type Hello = ServerHello | ClientHello

// true or false.
export interface FlagRule {
  kind: 'flag'
}

// A whole number from low to high.
export interface WholeRule {
  kind: 'whole'
  low: number
  high: number
}

// One of the options.
export interface ChoiceRule {
  kind: 'choice'
  options: string[]
}

// One line of text: a name, a path, a build configuration or a connector's name.
export interface TextRule {
  kind: 'text'
  format: string
  max_length: number
  required: boolean
  example: string
}

// A list of web origins, such as http://localhost:3000.
export interface OriginsRule {
  kind: 'origins'
  max_items: number
}

// What a setting's value may be, told apart by kind.
export type RuleSpec = FlagRule | WholeRule | ChoiceRule | TextRule | OriginsRule

// A setting's value: a flag, a whole number, text, or a list of text.
export type SettingValue = boolean | number | string | string[]

export interface SettingOrigin {
  layer: SettingLayer
  // What in the layer set it: the file, the scope's table, or the variable.
  detail: string | null
}

// A tab of the panel: a top-level table of config.toml.
export interface SettingsSection {
  // The table's name; empty for the top of the file.
  id: string
  title: string
  doc: string
}

export interface SettingEntry {
  // Where it lives in config.toml, such as stream.fps.
  path: string
  section: string
  doc: string
  rule: RuleSpec
  value: SettingValue
  default: SettingValue
  origin: SettingOrigin
  effect: SettingEffect
  reach: SettingReach
  // It decides what SimMirror runs or who may reach it: a page changes it only once a person confirms at the
  // terminal.
  sensitive: boolean
  // Why it cannot be changed here -- such as a variable setting it -- or null when it can.
  locked: string | null
  // How to change it at the terminal instead.
  command: string
}

// Every setting as a scope sees it, grouped into sections, and what the asker may do with them.
export interface SettingsView {
  scope: string
  access: SettingsAccess
  // What the asker should know before changing anything -- such as how to open settings that may be changed -- or
  // null.
  notice: string | null
  sections: SettingsSection[]
  settings: SettingEntry[]
}

export interface SettingValueChange {
  path: string
  value: SettingValue
}

// Values to set and settings to put back to what the layer below says, all or none.
export interface SettingsChange {
  target: SettingsTarget
  set: SettingValueChange[]
  unset: string[]
  // The code `sim-mirror settings confirm` printed, for a change that includes a sensitive setting.
  confirmation: string | null
}

export interface SettingsProblem {
  path: string
  message: string
}

// A sensitive change waiting for a person to confirm it at the terminal.
export interface PendingConfirmation {
  id: string
  // What the change does, as the terminal shows it.
  summary: string
  // The command that shows the change and its code.
  command: string
  expires_in_s: number
}

// A change refused, with each setting's problem, or the confirmation it waits for.
export interface SettingsRefusal {
  detail: string
  errors: SettingsProblem[]
  confirmation: PendingConfirmation | null
}

export interface ScopeStatusStream {
  encoding: EncodingSetting
  fps: number
}

export interface ScopeStatusCursor {
  enabled: boolean
  lead_ms: number
}

// Whether a scope can have a simulator, why not, how its device stands, and what the viewer is offered. The HTTP
// status route answers with it.
export interface ScopeStatus {
  enabled: boolean
  // Why the scope cannot have a simulator now; null when it can.
  reason: string | null
  device: Device | null
  stream: ScopeStatusStream
  cursor: ScopeStatusCursor
  // The connector that drives devices for this scope; null when none is available.
  connector: string | null
  capabilities: Capability[]
  // Why a connector other than the one asked for is in use; null otherwise.
  fallback_reason: string | null
}

// A scope's status once its device is being brought up, with a one-shot ticket for its screen socket.
export interface Started extends ScopeStatus {
  ticket: string
}

// A simulator on this Mac a scope could use, for a device picker.
export interface DeviceChoice {
  udid: string
  name: string
  runtime: string
  // What simctl says, such as Booted or Shutdown.
  state: string
  created: boolean
}

// How the device stands: sent on the screen socket after the stream starts, and whenever that changes.
export interface StatusEvent extends Device {
  type: 'status'
}

// The encoding the server chose from the client's hello. Binary frames in that encoding follow.
export interface StreamStart {
  type: 'stream'
  encoding: Encoding
}
