// SPDX-License-Identifier: Apache-2.0
// The screen socket protocol, version 1: its constants and message types.
// Generated by scripts/gen_protocol.py from protocol/v1 -- do not edit.

export const PROTOCOL_VERSION = 1
export const TAG_JPEG = 1
export const TAG_H264 = 2
export const MESSAGE_MAX_BYTES = 4096
export const TEXT_MAX_CHARS = 2000
export const SCROLL_MAX_PT = 600
export const TICKET_TTL_S = 60
export const HELLO_TIMEOUT_S = 10
export const WORKING_EVERY_S = 10
export const SCREEN_TEXT_MAX_BOXES = 200
export const CLOSE_BAD_GATEWAY = 1014
export const CLOSE_BAD_MESSAGE = 4400
export const CLOSE_UNAUTHORIZED = 4401
export const CLOSE_FORBIDDEN = 4403
export const CLOSE_UNSUPPORTED = 4406
export const CLOSE_STOPPED = 4410
export const CLOSE_RESTARTING = 4412

// A finger going down, moving, lifting, or taken away without lifting.
export const TOUCH_PHASES = ['down', 'move', 'up', 'cancel'] as const
export type TouchPhase = (typeof TOUCH_PHASES)[number]

// The hardware buttons a person may press from a viewer.
export const PANEL_BUTTONS = ['home', 'lock', 'side', 'siri'] as const
export type PanelButton = (typeof PANEL_BUTTONS)[number]

// Keys that are not text. Text is sent whole, as a text input.
export const KEY_NAMES = ['return', 'escape', 'delete', 'tab', 'space', 'right', 'left', 'down', 'up'] as const
export type KeyName = (typeof KEY_NAMES)[number]

// The device's appearance.
export const APPEARANCES = ['light', 'dark'] as const
export type Appearance = (typeof APPEARANCES)[number]

// Something a connector can do with a device. The viewer and the agent tools offer only what the connector in use
// can do.
export const CAPABILITIES = ['lifecycle', 'device_list', 'appearance', 'open_url', 'app_install', 'app_launch', 'logs', 'screenshot', 'stream_jpeg', 'stream_h264', 'input_touch', 'input_button', 'input_key', 'input_text', 'element_tree', 'build_preview', 'record', 'status_bar', 'location', 'accessibility'] as const
export type Capability = (typeof CAPABILITIES)[number]

// What a device is: a simulator on this Mac, or a real iPhone or iPad connected to it.
export const DEVICE_KINDS = ['simulator', 'physical'] as const
export type DeviceKind = (typeof DEVICE_KINDS)[number]

// How a real device reaches this Mac: by cable, or over the network.
export const CONNECTIONS = ['usb', 'network'] as const
export type Connection = (typeof CONNECTIONS)[number]

// How screen frames travel: JPEG images, or an H.264 Annex-B stream.
export const ENCODINGS = ['jpeg', 'h264'] as const
export type Encoding = (typeof ENCODINGS)[number]

// The encoding a scope asks for. auto is H.264 where the viewer can decode it, JPEG where it cannot.
export const ENCODING_SETTINGS = ['auto', 'jpeg', 'h264'] as const
export type EncodingSetting = (typeof ENCODING_SETTINGS)[number]

// How a device stands: being brought up, streaming and taking input, running but failing to stream, unable to
// start, or gone.
export const DEVICE_STATES = ['booting', 'ready', 'stalled', 'failed', 'stopped'] as const
export type DeviceState = (typeof DEVICE_STATES)[number]

// What a token is for: an agent's tools, a person's viewer, a host's namespaces, or everything.
export const TOKEN_KINDS = ['agent', 'viewer', 'admin', 'host'] as const
export type TokenKind = (typeof TOKEN_KINDS)[number]

// What a spent login code or embed ticket opens: a viewer, a framed viewer, or a viewer that may change settings.
export const SESSION_KINDS = ['viewer', 'embed', 'settings'] as const
export type SessionKind = (typeof SESSION_KINDS)[number]

// How touching a scope's real device stands: nothing to set up (a simulator, or none running), WebDriverAgent
// turned off, touch working, no team known to sign WebDriverAgent, a person's Set up touch offered, WebDriverAgent
// being built, being started on the device, or failed and why.
export const TOUCH_SETUP_STATES = ['not_needed', 'off', 'ready', 'needs_team', 'offer', 'building', 'starting', 'failed'] as const
export type TouchSetupState = (typeof TOUCH_SETUP_STATES)[number]

// Where the team that signs for a real device came from: the scope's project, real_devices.team_id, or the only
// team this Mac signs for.
export const TEAM_SOURCES = ['project', 'setting', 'mac'] as const
export type TeamSource = (typeof TEAM_SOURCES)[number]

// When a change takes effect: at once, on a viewer's next connection, on the device next brought up, or when the
// daemon restarts.
export const SETTING_EFFECTS = ['live', 'next_connection', 'next_device', 'restart'] as const
export type SettingEffect = (typeof SETTING_EFFECTS)[number]

// Whom a setting is for: each scope, or only the whole daemon.
export const SETTING_REACHES = ['scope', 'global'] as const
export type SettingReach = (typeof SETTING_REACHES)[number]

// Where a value comes from, lowest first: the default, config.toml, the scope's table in it, a SIM_MIRROR_*
// variable, or the command line.
export const SETTING_LAYERS = ['default', 'file', 'scope', 'environment', 'command_line'] as const
export type SettingLayer = (typeof SETTING_LAYERS)[number]

// What the asker may do: read only, change what is not sensitive, or change everything.
export const SETTINGS_ACCESS = ['read', 'write', 'write_sensitive'] as const
export type SettingsAccess = (typeof SETTINGS_ACCESS)[number]

// Whether a change is for this scope alone or for every scope.
export const SETTINGS_TARGETS = ['scope', 'all'] as const
export type SettingsTarget = (typeof SETTINGS_TARGETS)[number]

// A fraction of the screen: 0 at its left or top edge, 1 at its right or bottom edge.
export type Share = number

// A point on the screen as fractions of its width and height.
export type Point = [Share, Share]

// The gesture an intent announces.
export interface Gesture {
  // What it is: tap, long_press, swipe, drag, type, press, look, app or build. A viewer draws kinds it does not
  // know as a caption.
  kind: string
  duration_ms: number
  // Where it lands, in order; empty for a gesture with no place on the screen.
  points: Point[]
}

// A gesture about to land. While anyone watches, the server waits lead_ms after sending it, so the pointer arrives
// first.
export interface AgentIntent {
  type: 'agent'
  id: string
  phase: 'intent'
  agent: Agent
  // False when the agent cursor is off: an agent is using the device, and nothing is drawn.
  pointer: boolean
  // The label of the element the gesture lands on, if it has one.
  label: string
  caption: string
  lead_ms: number
  // How long the pointer stays, resting where it last acted, after the agent's last event. 0: only while the
  // gesture is drawn.
  linger_ms: number
  gesture: Gesture
}

// The gesture an intent announced is over.
export interface AgentDone {
  type: 'agent'
  id: string
  phase: 'done'
  ok: boolean
}

// An agent is still at work on the device -- a tool call has started, is running, or has just ended -- with nothing
// new to draw. Sent when a call starts and ends, and every WORKING_EVERY_S while a long one, such as a build or a
// test run, goes on.
export interface AgentWorking {
  type: 'agent'
  id: string
  phase: 'working'
  agent: Agent
  // True while the call runs, when another of these follows within WORKING_EVERY_S; false once it has ended.
  ongoing: boolean
  linger_ms: number
}

// What an agent is about to do on the device, whether it worked, and that it is still working. A viewer draws the
// intent with its own pointer, and keeps it while the agent works.
export type AgentEvent = AgentIntent | AgentDone | AgentWorking

// One finger's touch. A down, its moves and its up are one gesture on the device.
export interface TouchInput {
  type: 'touch'
  phase: TouchPhase
  nx: Share
  ny: Share
}

// A scroll wheel's movement at a point.
export interface ScrollInput {
  type: 'scroll'
  nx: Share
  ny: Share
  // How far the content moves, in points; positive scrolls down. The server clamps it to scroll_max_pt either way.
  dy: number
}

export interface ButtonInput {
  type: 'button'
  name: PanelButton
}

export interface KeyInput {
  type: 'key'
  name: KeyName
}

// Text for the focused field. It is typed as key presses, or put on the device's pasteboard and pasted, as the
// scope's device.typing setting says.
export interface TextInput {
  type: 'text'
  text: string
}

export interface AppearanceInput {
  type: 'appearance'
  mode: Appearance
}

// What a person does to the screen, sent by the viewer after the hello. The server acts on these and nothing else,
// and ignores any other message.
export type ClientInput = TouchInput | ScrollInput | ButtonInput | KeyInput | TextInput | AppearanceInput

// A width and a height.
export interface Size {
  w: number
  h: number
}

// A device's screen: in points, which touches and snapshots use, and in pixels, which frames use.
export interface Screen {
  points: Size
  pixels: Size
  scale: number
}

// A running device, as a viewer is told about it.
export interface Device {
  // The device's identifier: a simulator's UDID, or a real device's hardware UDID.
  udid: string
  name: string
  // The runtime as a person says it, such as iOS 26.5.
  runtime: string
  state: DeviceState
  // Why the device is stalled, failed or stopped; null otherwise.
  reason: string | null
  // How long the device has been in this state.
  since_ms: number
  // How many screen sockets watch the device.
  viewers: number
  // What the device is kept for while agents' gestures would get in its way, such as a test run; null otherwise.
  busy: string | null
  // Whether SimMirror created this device.
  created: boolean
  // Whether SimMirror booted this device, and so may shut it down.
  booted_by_us: boolean
  screen: Screen | null
  // The app in front sharing its view hierarchy through SimMirror's debug SDK, as an agent's last snapshot read it;
  // null when none does. An older server does not send it.
  app_hierarchy: AppHierarchy | null
  // Whether it is a simulator or a real device. An older server does not send it: read it as simulator.
  kind: DeviceKind
  // How a real device reaches this Mac; null for a simulator. An older server does not send it.
  connection: Connection | null
  // The recording of the device's screen under way; null when none is. An older server does not send it.
  recording: RecordingState | null
}

// A recording of a device's screen under way.
export interface RecordingState {
  id: string
  // How long it has been recording.
  since_ms: number
  // Who started it: an agent's title, or a person.
  by: string
  // How long it may run before it stops by itself.
  max_ms: number
}

// An app sharing its view hierarchy through SimMirror's debug SDK, so snapshots read what accessibility leaves out.
export interface AppHierarchy {
  // The app's name as the home screen shows it.
  name: string
  bundle_id: string
  // The version of the SDK the app was built with.
  sdk_version: string
}

// Who is acting on a device: an agent, by a key that stays the same for its connection, and the title a viewer
// shows.
export interface Agent {
  key: string
  title: string
}

// What the server offers, sent as soon as the socket is admitted.
export interface ServerHello {
  type: 'hello'
  v: 1
  // The server's name and version, such as sim-mirror/0.1.0.
  server: string
  encodings: Encoding[]
  // The connector driving the device, such as idb or simctl.
  connector: string
  capabilities: Capability[]
  // Why a connector other than the one asked for is in use; null otherwise.
  fallback_reason: string | null
}

// The client's answer: the encodings it decodes, most preferred first. A server ignores encodings it does not know.
export interface ClientHello {
  type: 'hello'
  v: 1
  encodings: Encoding[]
}

// The first message each way on a screen socket: the server says what it offers, and the client answers with the
// encodings it decodes, most preferred first.
export type Hello = ServerHello | ClientHello

// Why a request was refused, with its HTTP status. A body that is not the right shape has a list of what is wrong
// with it instead of one sentence.
export interface Refusal {
  detail: string | RefusalProblem[]
}

// One thing wrong with a request's body.
export interface RefusalProblem {
  msg: string
}

// GET /healthz: that the daemon is up. Given a nonce, proof that it holds the admin token; given a token's id too,
// proof that it knows that token.
export interface Health {
  server: string
  protocol: number
  port: number
  // HMAC-SHA256 of the nonce, keyed by the admin token; null when no nonce was given.
  proof: string | null
  // HMAC-SHA256 of the nonce, keyed by the hex SHA-256 of the named token; null when no nonce or no known token id
  // was given.
  token_proof: string | null
}

// DELETE on a scope: whether its device was running and has been let go.
export interface Stopped {
  stopped: boolean
}

// GET a scope's devices: the simulators it could use, for a picker.
export interface DeviceList {
  devices: DeviceChoice[]
}

// One file a recording was kept as.
export interface RecordingFile {
  // The file's name in the recordings folder; GET /recordings/{name} serves it.
  name: string
  // Where it is on this Mac.
  path: string
  format: 'mp4' | 'gif'
  bytes: number
  width: number
  height: number
}

// A recording of a device's screen that was kept.
export interface Recording {
  id: string
  // The name of the device recorded.
  device: string
  // When it began, as an ISO 8601 time in UTC.
  started_at: string
  // How long it plays.
  duration_ms: number
  files: RecordingFile[]
  // What a person should know about it, such as touches not drawn.
  notes: string[]
}

// GET a scope's recordings: those kept, newest first, and the one under way on its device.
export interface RecordingList {
  recordings: Recording[]
  recording: RecordingState | null
}

// GET a scope's /device/touch: whether its real device can be touched, and what a person can do. POST it: set touch
// up -- build WebDriverAgent for the device, or start it again when it is built -- answering how it then stands.
export interface TouchSetup {
  state: TouchSetupState
  // What to tell a person; empty when there is nothing to say.
  message: string
  // The team that signs WebDriverAgent here, when one is known.
  team: string | null
  team_from: TeamSource | null
}

// PUT a scope's device: the simulator it uses from now on.
export interface Chosen {
  udid: string
}

// POST a scope's embed tickets: the path a page frames, with a one-shot ticket in its fragment, and how long the
// ticket lasts.
export interface EmbedTicket {
  url: string
  expires_in_s: number
}

// POST /api/v1/auth/exchange: a viewer token for the scope a login code or embed ticket was for.
export interface Exchanged {
  token: string
  scope: string
  kind: SessionKind
  expires_in_s: number
}

// POST an agent's lease: its scope's device is not stopped as idle for this long.
export interface Lease {
  scope: string
  expires_in_s: number
}

// A token as it may be shown: never the token itself, nor its digest.
export interface TokenRecord {
  id: string
  kind: TokenKind
  // Scope ids, `name:*` for a namespace, or `*` for every scope.
  scopes: string[]
  label: string
  // The folders its agents may reach.
  roots: string[]
  // When it was made, in seconds since the epoch.
  created: number
  // The id of the host token that made it; empty when the admin did.
  host: string
}

// A token just made: its record, and the token itself, which is never shown again.
export interface MadeToken extends TokenRecord {
  token: string
}

// GET the tokens a host made.
export interface TokenList {
  tokens: TokenRecord[]
}

// DELETE a token: whether there was one to revoke.
export interface Revoked {
  revoked: boolean
}

// A tool as an MCP manifest lists it.
export interface AgentTool {
  name: string
  description: string
  // A JSON Schema of its arguments.
  inputSchema: Record<string, unknown>
}

// GET /api/v1/agent/manifest, not wrapped in an Answer: the tools an agent is offered and how to use them -- or
// none, and why, in instructions.
export interface AgentManifest {
  tools: AgentTool[]
  instructions: string
}

// Text in a tool result.
export interface TextContent {
  type: 'text'
  text: string
}

// An image in a tool result, base64-encoded.
export interface ImageContent {
  type: 'image'
  data: string
  mimeType: string
}

// POST /api/v1/agent/call, not wrapped in an Answer: an MCP tool result. A refused or failed call is a result with
// isError, not an HTTP error.
export interface ToolResult {
  content: (TextContent | ImageContent)[]
  isError: boolean
}

// A line of text read from the screen's pixels, and the box around it as shares of the screen.
export interface TextBox {
  text: string
  // How sure the reading is of the text.
  confidence: number
  x: Share
  y: Share
  w: Share
  h: Share
}

// The text a reading of the screen's pixels found, and where, while the scope's perception.ocr_overlay is on. Each
// replaces the last; one with no boxes clears them, sent when the screen is about to change or the overlay is
// turned off. A viewer draws the boxes over the screen, never into it.
export interface ScreenText {
  type: 'screen_text'
  id: string
  // The longest a viewer keeps the boxes, unless another ScreenText comes first. 0: until one does.
  hold_ms: number
  // In the order the text reads; empty to clear. At most SCREEN_TEXT_MAX_BOXES.
  boxes: TextBox[]
}

// true or false.
export interface FlagRule {
  kind: 'flag'
}

// A whole number from low to high.
export interface WholeRule {
  kind: 'whole'
  low: number
  high: number
}

// One of the options.
export interface ChoiceRule {
  kind: 'choice'
  options: string[]
}

// One line of text: a name, a path, a build configuration or a connector's name.
export interface TextRule {
  kind: 'text'
  format: string
  max_length: number
  required: boolean
  example: string
  // Values worth offering to pick from, such as the connectors installed; any other the rule allows may still be
  // typed.
  suggestions: string[] | null
}

// A list of web origins, such as http://localhost:3000.
export interface OriginsRule {
  kind: 'origins'
  max_items: number
}

// What a setting's value may be, told apart by kind.
export type RuleSpec = FlagRule | WholeRule | ChoiceRule | TextRule | OriginsRule

// A setting's value: a flag, a whole number, text, or a list of text.
export type SettingValue = boolean | number | string | string[]

export interface SettingOrigin {
  layer: SettingLayer
  // What in the layer set it: the file, the scope's table, or the variable.
  detail: string | null
}

// A tab of the panel: a top-level table of config.toml.
export interface SettingsSection {
  // The table's name; empty for the top of the file.
  id: string
  title: string
  doc: string
}

export interface SettingEntry {
  // Where it lives in config.toml, such as stream.fps.
  path: string
  section: string
  doc: string
  rule: RuleSpec
  value: SettingValue
  default: SettingValue
  origin: SettingOrigin
  effect: SettingEffect
  reach: SettingReach
  // It decides what SimMirror runs or who may reach it: a page changes it only once a person confirms at the
  // terminal.
  sensitive: boolean
  // Why it cannot be changed here -- such as a variable setting it -- or null when it can.
  locked: string | null
  // How to change it at the terminal instead.
  command: string
}

// Every setting as a scope sees it, grouped into sections, and what the asker may do with them.
export interface SettingsView {
  scope: string
  access: SettingsAccess
  // What the asker should know before changing anything -- such as how to open settings that may be changed -- or
  // null.
  notice: string | null
  sections: SettingsSection[]
  settings: SettingEntry[]
}

export interface SettingValueChange {
  path: string
  value: SettingValue
}

// Values to set and settings to put back to what the layer below says, all or none.
export interface SettingsChange {
  target: SettingsTarget
  set: SettingValueChange[]
  unset: string[]
  // The code `sim-mirror settings confirm` printed, for a change that includes a sensitive setting.
  confirmation: string | null
}

export interface SettingsProblem {
  path: string
  message: string
}

// A sensitive change waiting for a person to confirm it at the terminal.
export interface PendingConfirmation {
  id: string
  // What the change does, as the terminal shows it.
  summary: string
  // The command that shows the change and its code.
  command: string
  expires_in_s: number
}

// A change refused, with each setting's problem, or the confirmation it waits for.
export interface SettingsRefusal {
  detail: string
  errors: SettingsProblem[]
  confirmation: PendingConfirmation | null
}

export interface ScopeStatusStream {
  encoding: EncodingSetting
  fps: number
}

export interface ScopeStatusCursor {
  enabled: boolean
  lead_ms: number
}

// Whether a scope can have a simulator, why not, how its device stands, and what the viewer is offered. The HTTP
// status route answers with it.
export interface ScopeStatus {
  enabled: boolean
  // Why the scope cannot have a simulator now; null when it can.
  reason: string | null
  device: Device | null
  stream: ScopeStatusStream
  cursor: ScopeStatusCursor
  // The connector that drives devices for this scope; null when none is available.
  connector: string | null
  capabilities: Capability[]
  // Why a connector other than the one asked for is in use; null otherwise.
  fallback_reason: string | null
}

// A scope's status once its device is being brought up, with a one-shot ticket for its screen socket.
export interface Started extends ScopeStatus {
  ticket: string
}

// A device a scope could use, for a device picker: a simulator on this Mac, or a real device connected to it.
export interface DeviceChoice {
  udid: string
  name: string
  runtime: string
  // What simctl says of a simulator, such as Booted or Shutdown; Connected or Disconnected for a real device.
  state: string
  created: boolean
  // Whether it is a simulator or a real device. An older server does not send it: read it as simulator.
  kind: DeviceKind
  // How a real device reaches this Mac; null for a simulator.
  connection: Connection | null
  // What a person should know before picking it, such as Locked or Developer Mode off; null when nothing.
  detail: string | null
  // Whether it can be picked now; detail says why not. An older server does not send it: read it as true.
  usable: boolean
}

// How the device stands: sent on the screen socket after the stream starts, and whenever that changes.
export interface StatusEvent extends Device {
  type: 'status'
}

// The encoding the server chose from the client's hello. Binary frames in that encoding follow.
export interface StreamStart {
  type: 'stream'
  encoding: Encoding
}
