# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: sim_mirror/connectors/idb/proto/idb.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import sim_mirror.connectors.idb.proto.idb_pb2


class CompanionServiceBase(abc.ABC):

    @abc.abstractmethod
    async def connect(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.ConnectRequest, sim_mirror.connectors.idb.proto.idb_pb2.ConnectResponse]') -> None:
        pass

    @abc.abstractmethod
    async def debugserver(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.DebugServerRequest, sim_mirror.connectors.idb.proto.idb_pb2.DebugServerResponse]') -> None:
        pass

    @abc.abstractmethod
    async def dap(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.DapRequest, sim_mirror.connectors.idb.proto.idb_pb2.DapResponse]') -> None:
        pass

    @abc.abstractmethod
    async def describe(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.TargetDescriptionRequest, sim_mirror.connectors.idb.proto.idb_pb2.TargetDescriptionResponse]') -> None:
        pass

    @abc.abstractmethod
    async def install(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.InstallRequest, sim_mirror.connectors.idb.proto.idb_pb2.InstallResponse]') -> None:
        pass

    @abc.abstractmethod
    async def instruments_run(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.InstrumentsRunRequest, sim_mirror.connectors.idb.proto.idb_pb2.InstrumentsRunResponse]') -> None:
        pass

    @abc.abstractmethod
    async def log(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.LogRequest, sim_mirror.connectors.idb.proto.idb_pb2.LogResponse]') -> None:
        pass

    @abc.abstractmethod
    async def xctrace_record(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.XctraceRecordRequest, sim_mirror.connectors.idb.proto.idb_pb2.XctraceRecordResponse]') -> None:
        pass

    @abc.abstractmethod
    async def accessibility_info(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityInfoRequest, sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityInfoResponse]') -> None:
        pass

    @abc.abstractmethod
    async def accessibility_action(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityActionRequest, sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityActionResponse]') -> None:
        pass

    @abc.abstractmethod
    async def focus(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.FocusRequest, sim_mirror.connectors.idb.proto.idb_pb2.FocusResponse]') -> None:
        pass

    @abc.abstractmethod
    async def hid(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.HIDEvent, sim_mirror.connectors.idb.proto.idb_pb2.HIDResponse]') -> None:
        pass

    @abc.abstractmethod
    async def open_url(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.OpenUrlRequest, sim_mirror.connectors.idb.proto.idb_pb2.OpenUrlRequest]') -> None:
        pass

    @abc.abstractmethod
    async def set_location(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.SetLocationRequest, sim_mirror.connectors.idb.proto.idb_pb2.SetLocationResponse]') -> None:
        pass

    @abc.abstractmethod
    async def send_notification(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.SendNotificationRequest, sim_mirror.connectors.idb.proto.idb_pb2.SendNotificationResponse]') -> None:
        pass

    @abc.abstractmethod
    async def simulate_memory_warning(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.SimulateMemoryWarningRequest, sim_mirror.connectors.idb.proto.idb_pb2.SimulateMemoryWarningResponse]') -> None:
        pass

    @abc.abstractmethod
    async def approve(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.ApproveRequest, sim_mirror.connectors.idb.proto.idb_pb2.ApproveResponse]') -> None:
        pass

    @abc.abstractmethod
    async def revoke(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.RevokeRequest, sim_mirror.connectors.idb.proto.idb_pb2.RevokeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def clear_keychain(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.ClearKeychainRequest, sim_mirror.connectors.idb.proto.idb_pb2.ClearKeychainResponse]') -> None:
        pass

    @abc.abstractmethod
    async def contacts_update(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.ContactsUpdateRequest, sim_mirror.connectors.idb.proto.idb_pb2.ContactsUpdateResponse]') -> None:
        pass

    @abc.abstractmethod
    async def contacts_clear(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.ContactsClearRequest, sim_mirror.connectors.idb.proto.idb_pb2.ContactsClearResponse]') -> None:
        pass

    @abc.abstractmethod
    async def photos_clear(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.PhotosClearRequest, sim_mirror.connectors.idb.proto.idb_pb2.PhotosClearResponse]') -> None:
        pass

    @abc.abstractmethod
    async def setting(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.SettingRequest, sim_mirror.connectors.idb.proto.idb_pb2.SettingResponse]') -> None:
        pass

    @abc.abstractmethod
    async def get_setting(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.GetSettingRequest, sim_mirror.connectors.idb.proto.idb_pb2.GetSettingResponse]') -> None:
        pass

    @abc.abstractmethod
    async def list_settings(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.ListSettingRequest, sim_mirror.connectors.idb.proto.idb_pb2.ListSettingResponse]') -> None:
        pass

    @abc.abstractmethod
    async def launch(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.LaunchRequest, sim_mirror.connectors.idb.proto.idb_pb2.LaunchResponse]') -> None:
        pass

    @abc.abstractmethod
    async def list_apps(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.ListAppsRequest, sim_mirror.connectors.idb.proto.idb_pb2.ListAppsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def terminate(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.TerminateRequest, sim_mirror.connectors.idb.proto.idb_pb2.TerminateResponse]') -> None:
        pass

    @abc.abstractmethod
    async def uninstall(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.UninstallRequest, sim_mirror.connectors.idb.proto.idb_pb2.UninstallResponse]') -> None:
        pass

    @abc.abstractmethod
    async def add_media(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.AddMediaRequest, sim_mirror.connectors.idb.proto.idb_pb2.AddMediaResponse]') -> None:
        pass

    @abc.abstractmethod
    async def record(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.RecordRequest, sim_mirror.connectors.idb.proto.idb_pb2.RecordResponse]') -> None:
        pass

    @abc.abstractmethod
    async def screenshot(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.ScreenshotRequest, sim_mirror.connectors.idb.proto.idb_pb2.ScreenshotResponse]') -> None:
        pass

    @abc.abstractmethod
    async def video_stream(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.VideoStreamRequest, sim_mirror.connectors.idb.proto.idb_pb2.VideoStreamResponse]') -> None:
        pass

    @abc.abstractmethod
    async def crash_delete(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.CrashLogQuery, sim_mirror.connectors.idb.proto.idb_pb2.CrashLogResponse]') -> None:
        pass

    @abc.abstractmethod
    async def crash_list(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.CrashLogQuery, sim_mirror.connectors.idb.proto.idb_pb2.CrashLogResponse]') -> None:
        pass

    @abc.abstractmethod
    async def crash_show(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.CrashShowRequest, sim_mirror.connectors.idb.proto.idb_pb2.CrashShowResponse]') -> None:
        pass

    @abc.abstractmethod
    async def xctest_list_bundles(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.XctestListBundlesRequest, sim_mirror.connectors.idb.proto.idb_pb2.XctestListBundlesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def xctest_list_tests(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.XctestListTestsRequest, sim_mirror.connectors.idb.proto.idb_pb2.XctestListTestsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def xctest_run(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.XctestRunRequest, sim_mirror.connectors.idb.proto.idb_pb2.XctestRunResponse]') -> None:
        pass

    @abc.abstractmethod
    async def repl(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.ReplRequest, sim_mirror.connectors.idb.proto.idb_pb2.ReplResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ls(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.LsRequest, sim_mirror.connectors.idb.proto.idb_pb2.LsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def mkdir(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.MkdirRequest, sim_mirror.connectors.idb.proto.idb_pb2.MkdirResponse]') -> None:
        pass

    @abc.abstractmethod
    async def mv(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.MvRequest, sim_mirror.connectors.idb.proto.idb_pb2.MvResponse]') -> None:
        pass

    @abc.abstractmethod
    async def rm(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.RmRequest, sim_mirror.connectors.idb.proto.idb_pb2.RmResponse]') -> None:
        pass

    @abc.abstractmethod
    async def pull(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.PullRequest, sim_mirror.connectors.idb.proto.idb_pb2.PullResponse]') -> None:
        pass

    @abc.abstractmethod
    async def push(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.PushRequest, sim_mirror.connectors.idb.proto.idb_pb2.PushResponse]') -> None:
        pass

    @abc.abstractmethod
    async def tail(self, stream: 'grpclib.server.Stream[sim_mirror.connectors.idb.proto.idb_pb2.TailRequest, sim_mirror.connectors.idb.proto.idb_pb2.TailResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/idb.CompanionService/connect': grpclib.const.Handler(
                self.connect,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.ConnectRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.ConnectResponse,
            ),
            '/idb.CompanionService/debugserver': grpclib.const.Handler(
                self.debugserver,
                grpclib.const.Cardinality.STREAM_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.DebugServerRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.DebugServerResponse,
            ),
            '/idb.CompanionService/dap': grpclib.const.Handler(
                self.dap,
                grpclib.const.Cardinality.STREAM_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.DapRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.DapResponse,
            ),
            '/idb.CompanionService/describe': grpclib.const.Handler(
                self.describe,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.TargetDescriptionRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.TargetDescriptionResponse,
            ),
            '/idb.CompanionService/install': grpclib.const.Handler(
                self.install,
                grpclib.const.Cardinality.STREAM_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.InstallRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.InstallResponse,
            ),
            '/idb.CompanionService/instruments_run': grpclib.const.Handler(
                self.instruments_run,
                grpclib.const.Cardinality.STREAM_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.InstrumentsRunRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.InstrumentsRunResponse,
            ),
            '/idb.CompanionService/log': grpclib.const.Handler(
                self.log,
                grpclib.const.Cardinality.UNARY_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.LogRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.LogResponse,
            ),
            '/idb.CompanionService/xctrace_record': grpclib.const.Handler(
                self.xctrace_record,
                grpclib.const.Cardinality.STREAM_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.XctraceRecordRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.XctraceRecordResponse,
            ),
            '/idb.CompanionService/accessibility_info': grpclib.const.Handler(
                self.accessibility_info,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityInfoRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityInfoResponse,
            ),
            '/idb.CompanionService/accessibility_action': grpclib.const.Handler(
                self.accessibility_action,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityActionRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityActionResponse,
            ),
            '/idb.CompanionService/focus': grpclib.const.Handler(
                self.focus,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.FocusRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.FocusResponse,
            ),
            '/idb.CompanionService/hid': grpclib.const.Handler(
                self.hid,
                grpclib.const.Cardinality.STREAM_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.HIDEvent,
                sim_mirror.connectors.idb.proto.idb_pb2.HIDResponse,
            ),
            '/idb.CompanionService/open_url': grpclib.const.Handler(
                self.open_url,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.OpenUrlRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.OpenUrlRequest,
            ),
            '/idb.CompanionService/set_location': grpclib.const.Handler(
                self.set_location,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.SetLocationRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.SetLocationResponse,
            ),
            '/idb.CompanionService/send_notification': grpclib.const.Handler(
                self.send_notification,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.SendNotificationRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.SendNotificationResponse,
            ),
            '/idb.CompanionService/simulate_memory_warning': grpclib.const.Handler(
                self.simulate_memory_warning,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.SimulateMemoryWarningRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.SimulateMemoryWarningResponse,
            ),
            '/idb.CompanionService/approve': grpclib.const.Handler(
                self.approve,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.ApproveRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.ApproveResponse,
            ),
            '/idb.CompanionService/revoke': grpclib.const.Handler(
                self.revoke,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.RevokeRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.RevokeResponse,
            ),
            '/idb.CompanionService/clear_keychain': grpclib.const.Handler(
                self.clear_keychain,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.ClearKeychainRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.ClearKeychainResponse,
            ),
            '/idb.CompanionService/contacts_update': grpclib.const.Handler(
                self.contacts_update,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.ContactsUpdateRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.ContactsUpdateResponse,
            ),
            '/idb.CompanionService/contacts_clear': grpclib.const.Handler(
                self.contacts_clear,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.ContactsClearRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.ContactsClearResponse,
            ),
            '/idb.CompanionService/photos_clear': grpclib.const.Handler(
                self.photos_clear,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.PhotosClearRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.PhotosClearResponse,
            ),
            '/idb.CompanionService/setting': grpclib.const.Handler(
                self.setting,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.SettingRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.SettingResponse,
            ),
            '/idb.CompanionService/get_setting': grpclib.const.Handler(
                self.get_setting,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.GetSettingRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.GetSettingResponse,
            ),
            '/idb.CompanionService/list_settings': grpclib.const.Handler(
                self.list_settings,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.ListSettingRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.ListSettingResponse,
            ),
            '/idb.CompanionService/launch': grpclib.const.Handler(
                self.launch,
                grpclib.const.Cardinality.STREAM_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.LaunchRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.LaunchResponse,
            ),
            '/idb.CompanionService/list_apps': grpclib.const.Handler(
                self.list_apps,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.ListAppsRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.ListAppsResponse,
            ),
            '/idb.CompanionService/terminate': grpclib.const.Handler(
                self.terminate,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.TerminateRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.TerminateResponse,
            ),
            '/idb.CompanionService/uninstall': grpclib.const.Handler(
                self.uninstall,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.UninstallRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.UninstallResponse,
            ),
            '/idb.CompanionService/add_media': grpclib.const.Handler(
                self.add_media,
                grpclib.const.Cardinality.STREAM_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.AddMediaRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.AddMediaResponse,
            ),
            '/idb.CompanionService/record': grpclib.const.Handler(
                self.record,
                grpclib.const.Cardinality.STREAM_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.RecordRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.RecordResponse,
            ),
            '/idb.CompanionService/screenshot': grpclib.const.Handler(
                self.screenshot,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.ScreenshotRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.ScreenshotResponse,
            ),
            '/idb.CompanionService/video_stream': grpclib.const.Handler(
                self.video_stream,
                grpclib.const.Cardinality.STREAM_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.VideoStreamRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.VideoStreamResponse,
            ),
            '/idb.CompanionService/crash_delete': grpclib.const.Handler(
                self.crash_delete,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.CrashLogQuery,
                sim_mirror.connectors.idb.proto.idb_pb2.CrashLogResponse,
            ),
            '/idb.CompanionService/crash_list': grpclib.const.Handler(
                self.crash_list,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.CrashLogQuery,
                sim_mirror.connectors.idb.proto.idb_pb2.CrashLogResponse,
            ),
            '/idb.CompanionService/crash_show': grpclib.const.Handler(
                self.crash_show,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.CrashShowRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.CrashShowResponse,
            ),
            '/idb.CompanionService/xctest_list_bundles': grpclib.const.Handler(
                self.xctest_list_bundles,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.XctestListBundlesRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.XctestListBundlesResponse,
            ),
            '/idb.CompanionService/xctest_list_tests': grpclib.const.Handler(
                self.xctest_list_tests,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.XctestListTestsRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.XctestListTestsResponse,
            ),
            '/idb.CompanionService/xctest_run': grpclib.const.Handler(
                self.xctest_run,
                grpclib.const.Cardinality.UNARY_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.XctestRunRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.XctestRunResponse,
            ),
            '/idb.CompanionService/repl': grpclib.const.Handler(
                self.repl,
                grpclib.const.Cardinality.STREAM_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.ReplRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.ReplResponse,
            ),
            '/idb.CompanionService/ls': grpclib.const.Handler(
                self.ls,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.LsRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.LsResponse,
            ),
            '/idb.CompanionService/mkdir': grpclib.const.Handler(
                self.mkdir,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.MkdirRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.MkdirResponse,
            ),
            '/idb.CompanionService/mv': grpclib.const.Handler(
                self.mv,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.MvRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.MvResponse,
            ),
            '/idb.CompanionService/rm': grpclib.const.Handler(
                self.rm,
                grpclib.const.Cardinality.UNARY_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.RmRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.RmResponse,
            ),
            '/idb.CompanionService/pull': grpclib.const.Handler(
                self.pull,
                grpclib.const.Cardinality.UNARY_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.PullRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.PullResponse,
            ),
            '/idb.CompanionService/push': grpclib.const.Handler(
                self.push,
                grpclib.const.Cardinality.STREAM_UNARY,
                sim_mirror.connectors.idb.proto.idb_pb2.PushRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.PushResponse,
            ),
            '/idb.CompanionService/tail': grpclib.const.Handler(
                self.tail,
                grpclib.const.Cardinality.STREAM_STREAM,
                sim_mirror.connectors.idb.proto.idb_pb2.TailRequest,
                sim_mirror.connectors.idb.proto.idb_pb2.TailResponse,
            ),
        }


class CompanionServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.connect = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/connect',
            sim_mirror.connectors.idb.proto.idb_pb2.ConnectRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.ConnectResponse,
        )
        self.debugserver = grpclib.client.StreamStreamMethod(
            channel,
            '/idb.CompanionService/debugserver',
            sim_mirror.connectors.idb.proto.idb_pb2.DebugServerRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.DebugServerResponse,
        )
        self.dap = grpclib.client.StreamStreamMethod(
            channel,
            '/idb.CompanionService/dap',
            sim_mirror.connectors.idb.proto.idb_pb2.DapRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.DapResponse,
        )
        self.describe = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/describe',
            sim_mirror.connectors.idb.proto.idb_pb2.TargetDescriptionRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.TargetDescriptionResponse,
        )
        self.install = grpclib.client.StreamStreamMethod(
            channel,
            '/idb.CompanionService/install',
            sim_mirror.connectors.idb.proto.idb_pb2.InstallRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.InstallResponse,
        )
        self.instruments_run = grpclib.client.StreamStreamMethod(
            channel,
            '/idb.CompanionService/instruments_run',
            sim_mirror.connectors.idb.proto.idb_pb2.InstrumentsRunRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.InstrumentsRunResponse,
        )
        self.log = grpclib.client.UnaryStreamMethod(
            channel,
            '/idb.CompanionService/log',
            sim_mirror.connectors.idb.proto.idb_pb2.LogRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.LogResponse,
        )
        self.xctrace_record = grpclib.client.StreamStreamMethod(
            channel,
            '/idb.CompanionService/xctrace_record',
            sim_mirror.connectors.idb.proto.idb_pb2.XctraceRecordRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.XctraceRecordResponse,
        )
        self.accessibility_info = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/accessibility_info',
            sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityInfoRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityInfoResponse,
        )
        self.accessibility_action = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/accessibility_action',
            sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityActionRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.AccessibilityActionResponse,
        )
        self.focus = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/focus',
            sim_mirror.connectors.idb.proto.idb_pb2.FocusRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.FocusResponse,
        )
        self.hid = grpclib.client.StreamUnaryMethod(
            channel,
            '/idb.CompanionService/hid',
            sim_mirror.connectors.idb.proto.idb_pb2.HIDEvent,
            sim_mirror.connectors.idb.proto.idb_pb2.HIDResponse,
        )
        self.open_url = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/open_url',
            sim_mirror.connectors.idb.proto.idb_pb2.OpenUrlRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.OpenUrlRequest,
        )
        self.set_location = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/set_location',
            sim_mirror.connectors.idb.proto.idb_pb2.SetLocationRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.SetLocationResponse,
        )
        self.send_notification = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/send_notification',
            sim_mirror.connectors.idb.proto.idb_pb2.SendNotificationRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.SendNotificationResponse,
        )
        self.simulate_memory_warning = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/simulate_memory_warning',
            sim_mirror.connectors.idb.proto.idb_pb2.SimulateMemoryWarningRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.SimulateMemoryWarningResponse,
        )
        self.approve = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/approve',
            sim_mirror.connectors.idb.proto.idb_pb2.ApproveRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.ApproveResponse,
        )
        self.revoke = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/revoke',
            sim_mirror.connectors.idb.proto.idb_pb2.RevokeRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.RevokeResponse,
        )
        self.clear_keychain = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/clear_keychain',
            sim_mirror.connectors.idb.proto.idb_pb2.ClearKeychainRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.ClearKeychainResponse,
        )
        self.contacts_update = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/contacts_update',
            sim_mirror.connectors.idb.proto.idb_pb2.ContactsUpdateRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.ContactsUpdateResponse,
        )
        self.contacts_clear = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/contacts_clear',
            sim_mirror.connectors.idb.proto.idb_pb2.ContactsClearRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.ContactsClearResponse,
        )
        self.photos_clear = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/photos_clear',
            sim_mirror.connectors.idb.proto.idb_pb2.PhotosClearRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.PhotosClearResponse,
        )
        self.setting = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/setting',
            sim_mirror.connectors.idb.proto.idb_pb2.SettingRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.SettingResponse,
        )
        self.get_setting = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/get_setting',
            sim_mirror.connectors.idb.proto.idb_pb2.GetSettingRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.GetSettingResponse,
        )
        self.list_settings = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/list_settings',
            sim_mirror.connectors.idb.proto.idb_pb2.ListSettingRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.ListSettingResponse,
        )
        self.launch = grpclib.client.StreamStreamMethod(
            channel,
            '/idb.CompanionService/launch',
            sim_mirror.connectors.idb.proto.idb_pb2.LaunchRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.LaunchResponse,
        )
        self.list_apps = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/list_apps',
            sim_mirror.connectors.idb.proto.idb_pb2.ListAppsRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.ListAppsResponse,
        )
        self.terminate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/terminate',
            sim_mirror.connectors.idb.proto.idb_pb2.TerminateRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.TerminateResponse,
        )
        self.uninstall = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/uninstall',
            sim_mirror.connectors.idb.proto.idb_pb2.UninstallRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.UninstallResponse,
        )
        self.add_media = grpclib.client.StreamUnaryMethod(
            channel,
            '/idb.CompanionService/add_media',
            sim_mirror.connectors.idb.proto.idb_pb2.AddMediaRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.AddMediaResponse,
        )
        self.record = grpclib.client.StreamStreamMethod(
            channel,
            '/idb.CompanionService/record',
            sim_mirror.connectors.idb.proto.idb_pb2.RecordRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.RecordResponse,
        )
        self.screenshot = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/screenshot',
            sim_mirror.connectors.idb.proto.idb_pb2.ScreenshotRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.ScreenshotResponse,
        )
        self.video_stream = grpclib.client.StreamStreamMethod(
            channel,
            '/idb.CompanionService/video_stream',
            sim_mirror.connectors.idb.proto.idb_pb2.VideoStreamRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.VideoStreamResponse,
        )
        self.crash_delete = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/crash_delete',
            sim_mirror.connectors.idb.proto.idb_pb2.CrashLogQuery,
            sim_mirror.connectors.idb.proto.idb_pb2.CrashLogResponse,
        )
        self.crash_list = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/crash_list',
            sim_mirror.connectors.idb.proto.idb_pb2.CrashLogQuery,
            sim_mirror.connectors.idb.proto.idb_pb2.CrashLogResponse,
        )
        self.crash_show = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/crash_show',
            sim_mirror.connectors.idb.proto.idb_pb2.CrashShowRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.CrashShowResponse,
        )
        self.xctest_list_bundles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/xctest_list_bundles',
            sim_mirror.connectors.idb.proto.idb_pb2.XctestListBundlesRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.XctestListBundlesResponse,
        )
        self.xctest_list_tests = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/xctest_list_tests',
            sim_mirror.connectors.idb.proto.idb_pb2.XctestListTestsRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.XctestListTestsResponse,
        )
        self.xctest_run = grpclib.client.UnaryStreamMethod(
            channel,
            '/idb.CompanionService/xctest_run',
            sim_mirror.connectors.idb.proto.idb_pb2.XctestRunRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.XctestRunResponse,
        )
        self.repl = grpclib.client.StreamStreamMethod(
            channel,
            '/idb.CompanionService/repl',
            sim_mirror.connectors.idb.proto.idb_pb2.ReplRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.ReplResponse,
        )
        self.ls = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/ls',
            sim_mirror.connectors.idb.proto.idb_pb2.LsRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.LsResponse,
        )
        self.mkdir = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/mkdir',
            sim_mirror.connectors.idb.proto.idb_pb2.MkdirRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.MkdirResponse,
        )
        self.mv = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/mv',
            sim_mirror.connectors.idb.proto.idb_pb2.MvRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.MvResponse,
        )
        self.rm = grpclib.client.UnaryUnaryMethod(
            channel,
            '/idb.CompanionService/rm',
            sim_mirror.connectors.idb.proto.idb_pb2.RmRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.RmResponse,
        )
        self.pull = grpclib.client.UnaryStreamMethod(
            channel,
            '/idb.CompanionService/pull',
            sim_mirror.connectors.idb.proto.idb_pb2.PullRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.PullResponse,
        )
        self.push = grpclib.client.StreamUnaryMethod(
            channel,
            '/idb.CompanionService/push',
            sim_mirror.connectors.idb.proto.idb_pb2.PushRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.PushResponse,
        )
        self.tail = grpclib.client.StreamStreamMethod(
            channel,
            '/idb.CompanionService/tail',
            sim_mirror.connectors.idb.proto.idb_pb2.TailRequest,
            sim_mirror.connectors.idb.proto.idb_pb2.TailResponse,
        )
