# SPDX-License-Identifier: Apache-2.0
"""Write the reference pages that restate the code, from the code, so they cannot drift from it.

* ``docs/reference/tools.md`` -- every agent tool: what it does, what its connector must do, its arguments;
* ``docs/reference/configuration.md`` -- every setting, from `sim_mirror.config.schema`;
* ``docs/reference/cli.md`` -- every command and flag, from the argument parser;
* ``docs/reference/protocol.md`` -- the screen protocol's close codes and constants, from ``protocol/v1``;
* ``docs/compatibility.md`` -- where SimMirror is expected to work and where it was checked, from
  ``compat/matrix.toml``.

    uv run python scripts/gen_docs.py            # write them (`make generate`)
    uv run python scripts/gen_docs.py --check    # exit 1 if one is stale, writing nothing
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Iterable, Iterator, Mapping, Sequence
from pathlib import Path
from typing import Any

import tomlkit

from _repo import REPO_ROOT
from sim_mirror.build.provider import BuildToolProvider
from sim_mirror.cli.main import parser as cli_parser
from sim_mirror.config import schema
from sim_mirror.config.model import SimConfig
from sim_mirror.connectors.base import Capability
from sim_mirror.tools.context import Tool
from sim_mirror.tools.registry import DeviceToolProvider, ToolRegistry

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib

NOTICE = "<!-- Generated by scripts/gen_docs.py -- do not edit. Run `make generate` after changing its source. -->"
STATUS = re.compile(r"\A(expected|unsupported|verified \d{4}-\d{2}-\d{2})\Z")
MATRIX = "compat/matrix.toml"
PROTOCOL = "protocol/v1"
REPORT = "https://github.com/AndrewKochulab/sim-mirror/issues/new?template=compatibility-report.yml"
#: Each tool provider's tools, when they are offered, briefly and in full.
PROVIDERS: tuple[tuple[str, str, tuple[Tool, ...]], ...] = (
    ("always", "always", DeviceToolProvider.tools),
    (
        "with build tools",
        "while `build.tools` is on (a preview), and refused per call where the host allows no commands",
        BuildToolProvider.tools,
    ),
)


class SourceError(Exception):
    """A source of the pages that cannot be read as one."""


def page(title: str, *blocks: str) -> str:
    return "\n\n".join([f"# {title}", NOTICE, *blocks]).rstrip() + "\n"


def table(header: Sequence[str], rows: Iterable[Sequence[str]]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for row in rows:
        lines.append("| " + " | ".join(cell.replace("|", "\\|").replace("\n", " ") for cell in row) + " |")
    return "\n".join(lines)


# -- tools ---------------------------------------------------------------------------------------------------------


def argument_type(prop: Mapping[str, Any]) -> str:
    if "oneOf" in prop:
        return " or ".join(argument_type(option) for option in prop["oneOf"])
    kind = str(prop.get("type", "any"))
    if kind == "array":
        return f"array of {prop.get('items', {}).get('type', 'any')}"
    return kind


def allowed(prop: Mapping[str, Any]) -> str:
    parts: list[str] = []
    if "enum" in prop:
        parts.append(", ".join(f"`{value}`" for value in prop["enum"]))
    if "minimum" in prop and "maximum" in prop:
        parts.append(f"{prop['minimum']} to {prop['maximum']}")
    if "maxItems" in prop:
        parts.append(f"{prop.get('minItems', 0)} to {prop['maxItems']} items")
    if "description" in prop:
        parts.append(str(prop["description"]))
    return "; ".join(parts) or "—"


def needs_of(tool: Tool) -> str:
    return ", ".join(f"`{capability.value}`" for capability in sorted(tool.needs, key=lambda c: c.value)) or "nothing"


def tool_section(tool: Tool, offered: str) -> str:
    properties: Mapping[str, Any] = tool.input_schema.get("properties", {})
    required = set(tool.input_schema.get("required", []))
    rows = [
        (f"`{name}`", argument_type(prop), allowed(prop), "yes" if name in required else "no")
        for name, prop in properties.items()
    ]
    return "\n\n".join(
        [
            f"## `{tool.name}`",
            tool.description,
            f"Offered {offered}. Needs a connector that can do {needs_of(tool)}.",
            table(("Argument", "Type", "Allowed", "Required"), rows) if rows else "It takes no arguments.",
        ]
    )


def tools_page() -> str:
    summary = table(
        ("Tool", "Offered", "Needs"),
        [(f"[`{tool.name}`](#{tool.name})", brief, needs_of(tool)) for brief, _, tools in PROVIDERS for tool in tools],
    )
    registry = ToolRegistry()
    everything = frozenset(Capability)
    told = registry.manifest(SimConfig.defaults(), everything)["instructions"]
    told_with_builds = registry.manifest(SimConfig.defaults().with_values(build_tools=True), everything)["instructions"]
    return page(
        "Agent tools",
        "An MCP client lists these through `sim-mirror mcp`, or through a host application's relay. A tool the "
        "device's connector cannot serve is left out of the list, and a call to one anyway is refused with the "
        "connector's name and a pointer to `sim-mirror doctor`. What an answer costs an agent is in "
        "[Screen understanding](../screen-understanding.md).",
        summary,
        "## What a client is told\n\nWith build tools off:\n\n> "
        + told
        + "\n\nWith build tools on:\n\n> "
        + told_with_builds,
        *(tool_section(tool, full) for _, full, tools in PROVIDERS for tool in tools),
    )


# -- configuration -------------------------------------------------------------------------------------------------


def value(setting_value: Any) -> str:
    if isinstance(setting_value, bool):
        return f"`{str(setting_value).lower()}`"
    if isinstance(setting_value, (list, tuple)):
        return "`[" + ", ".join(json.dumps(item) for item in setting_value) + "]`"
    if setting_value == "":
        return "empty"
    return f"`{setting_value}`"


def section_of(setting: schema.Setting) -> str:
    return setting.path.rsplit(".", 1)[0] if "." in setting.path else ""


def setting_block(setting: schema.Setting) -> str:
    embedded = setting.default_for("embedded")
    lines = [
        f"### `{setting.path}`",
        "",
        setting.doc,
        "",
        f"- Default: {value(setting.default)}"
        + ("" if embedded == setting.default else f" (a host embedding SimMirror: {value(embedded)})"),
        f"- Allowed: {setting.rule.describe()}",
        f"- Environment: `{setting.env}`",
        f"- Key in a host's flat settings: `{setting.key}`",
    ]
    return "\n".join(lines)


def configuration_page() -> str:
    sections: dict[str, list[schema.Setting]] = {}
    for setting in schema.SETTINGS:
        sections.setdefault(section_of(setting), []).append(setting)
    defaults = json.loads(json.dumps(schema.nested(schema.defaults("standalone"))))
    blocks = [
        "SimMirror reads its settings on every operation, so a change applies to the next one. From lowest to highest "
        "precedence:\n\n"
        "1. the defaults below;\n"
        "2. `config.toml` -- `SIM_MIRROR_CONFIG`, else `~/Library/Application Support/SimMirror/config.toml` "
        "(`sim-mirror config path`);\n"
        '3. the file\'s `[scopes."<scope id>"]` table, for that scope;\n'
        "4. `SIM_MIRROR_*` environment variables;\n"
        "5. values given on the command line.\n\n"
        "A value its rule refuses is reported (`sim-mirror config validate`) and reads as the next lower one. "
        "`sim-mirror config set <setting> <value>` edits the file in place, keeping its comments, and tells a running "
        "daemon to reload -- a switch turned off is off before the command returns.",
        "## Defaults\n\n```toml\n" + tomlkit.dumps(defaults).strip() + "\n```",
    ]
    for name, settings in sections.items():
        blocks.append(f"## {f'`[{name}]`' if name else 'Top level'}\n\n" + "\n\n".join(map(setting_block, settings)))
    return page("Configuration", *blocks)


# -- command line --------------------------------------------------------------------------------------------------


def subcommands(made: argparse.ArgumentParser) -> list[tuple[str, str, argparse.ArgumentParser]]:
    found: list[tuple[str, str, argparse.ArgumentParser]] = []
    for action in made._actions:
        if isinstance(action, argparse._SubParsersAction):
            helps = {choice.dest: choice.help or "" for choice in action._choices_actions}
            found += [(name, helps.get(name, ""), sub) for name, sub in action.choices.items()]
    return found


def walk(made: argparse.ArgumentParser, prefix: str) -> Iterator[tuple[str, str, argparse.ArgumentParser]]:
    for name, said, sub in subcommands(made):
        path = f"{prefix} {name}"
        yield path, said, sub
        yield from walk(sub, path)


def arguments(made: argparse.ArgumentParser) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for action in made._actions:
        if isinstance(action, (argparse._HelpAction, argparse._VersionAction, argparse._SubParsersAction)):
            continue
        if action.option_strings:
            flag = ", ".join(action.option_strings)
            if action.nargs != 0:
                flag += f" {action.metavar or action.dest.upper()}"
        else:
            flag = str(action.metavar or action.dest).upper()
        said = action.help or ""
        if action.choices:
            said += f" (one of: {', '.join(map(str, action.choices))})"
        rows.append((f"`{flag}`", said))
    return rows


def sentence(text: str) -> str:
    """A command's help, which argparse keeps lower-case, as the start of a sentence."""
    return text[:1].upper() + text[1:]


def cli_page() -> str:
    made = cli_parser()
    commands = list(walk(made, "sim-mirror"))
    summary = table(("Command", "Does"), [(f"`{path}`", sentence(said)) for path, said, _ in commands])
    blocks = [
        "Every command answers `--help`. A refusal a person can act on -- a setting, a scope, a token, the daemon -- "
        "is one line on stderr and exit status 1. `sim-mirror --version` prints the version.",
        summary,
    ]
    for path, said, sub in commands:
        rows = arguments(sub)
        listed = table(("Argument", "Meaning"), rows) if rows else "It takes no arguments."
        blocks.append(f"## `{path}`\n\n{sentence(said)}.\n\n{listed}")
    return page("Command line", *blocks)


# -- protocol ------------------------------------------------------------------------------------------------------


def _json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise SourceError(f"cannot read {path.name}: {exc}") from exc


def protocol_page(root: Path) -> str:
    folder = root / PROTOCOL
    codes: Mapping[str, Any] = _json(folder / "close-codes.json").get("close_codes", {})
    constants: Mapping[str, Any] = _json(folder / "constants.json")
    return page(
        "Screen protocol",
        "How a viewer and a SimMirror server talk over the screen socket: a hello each way, then frames and events "
        "out and a whitelist of input in. The schemas in [`protocol/v1`](../../protocol/v1/) are the one definition "
        "-- the Python and TypeScript types are generated from them -- and [`protocol/README.md`]"
        "(../../protocol/README.md) walks through a socket's life and the rules for changing the protocol.",
        "## Close codes\n\n"
        + table(
            ("Code", "Constant", "Meaning"),
            [(f"`{entry['code']}`", f"`CLOSE_{name.upper()}`", str(entry["meaning"])) for name, entry in codes.items()],
        ),
        "## Constants\n\n"
        + table(
            ("Constant", "Value"),
            [(f"`{key.upper()}`", f"`{item}`") for key, item in constants.items() if not key.startswith("$")],
        ),
    )


# -- compatibility -------------------------------------------------------------------------------------------------


def _text(entry: Mapping[str, Any], key: str, where: str) -> str:
    found = entry.get(key)
    if not isinstance(found, str) or not found.strip():
        raise SourceError(f"{where}: `{key}` is text")
    return found


def compatibility_page(path: Path) -> str:
    try:
        matrix = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise SourceError(f"cannot read {path.name}: {exc}") from exc
    sections = matrix.get("section")
    if not isinstance(sections, list) or not sections:
        raise SourceError(f"{path.name}: lists at least one [[section]]")
    blocks = [
        "Where SimMirror is expected to work, and where it has been checked. A row says **verified**, with the date, "
        "only when it was checked end to end on real hardware; **expected** means it should work and nobody has "
        "checked it yet. Checked it yourself? Send a "
        f"[compatibility report]({REPORT}) with `sim-mirror doctor --json`."
    ]
    for section in sections:
        title = _text(section, "title", "a section")
        rows = []
        for row in section.get("row") or []:
            name = _text(row, "name", title)
            status = _text(row, "status", f"{title}: {name}")
            if not STATUS.match(status):
                raise SourceError(f"{title}: {name}: status is expected, unsupported or verified YYYY-MM-DD")
            rows.append((name, f"**{status}**", str(row.get("notes", ""))))
        if not rows:
            raise SourceError(f"{title}: has at least one row")
        note = str(section.get("note", "")).strip()
        blocks.append(
            f"## {title}\n\n"
            + (note + "\n\n" if note else "")
            + table((_text(section, "column", title), "Status", "Notes"), rows)
        )
    return page("Compatibility", *blocks)


# -- all -----------------------------------------------------------------------------------------------------------


def pages(root: Path) -> dict[Path, str]:
    return {
        root / "docs" / "reference" / "tools.md": tools_page(),
        root / "docs" / "reference" / "configuration.md": configuration_page(),
        root / "docs" / "reference" / "cli.md": cli_page(),
        root / "docs" / "reference" / "protocol.md": protocol_page(root),
        root / "docs" / "compatibility.md": compatibility_page(root / MATRIX),
    }


def main(argv: Sequence[str] | None = None, *, root: Path = REPO_ROOT) -> int:
    made = argparse.ArgumentParser(description="Write the reference pages generated from the code.")
    made.add_argument("--check", action="store_true", help="exit 1 if a page is stale, writing nothing")
    args = made.parse_args(argv)
    try:
        outputs = pages(root)
    except SourceError as exc:
        print(f"docs: {exc}", file=sys.stderr)
        return 2
    if args.check:
        stale = [
            path for path, text in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        for path in stale:
            print(f"stale: {path.relative_to(root)} -- run `make generate`", file=sys.stderr)
        return 1 if stale else 0
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
