# SPDX-License-Identifier: Apache-2.0
"""Generate the protocol's constants and types for Python and TypeScript from `protocol/v1/`.

`protocol/v1/` is the one definition of the screen socket and the HTTP routes' shapes: JSON Schemas, `constants.json`
and `close-codes.json`. This writes what each side imports from it:

* `src/sim_mirror/protocol/_generated.py` -- `Final` constants, `Literal` enums with a tuple of their values, and
  `TypedDict` messages;
* `viewer/src/protocol.generated.ts` -- the same as `const`s, types and interfaces.

It understands the subset of JSON Schema the protocol uses, and refuses anything else rather than guess: objects whose
every property is required (a value that can be absent is a nullable one), `allOf` of one reference and one object
(an extension), `oneOf`/`anyOf` of references (a union), `enum` definitions named with `x-constant`, `const`, `type`
lists, arrays, `prefixItems` tuples, `$ref` to a `$defs` entry of any file in the folder, and an object with
`"additionalProperties": true` and no properties, which is any JSON object (a tool's input schema).

    uv run python scripts/gen_protocol.py           # write the generated files
    uv run python scripts/gen_protocol.py --check   # exit 1 if either is stale
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, TypeVar

from _repo import REPO_ROOT

SCHEMA_DIR = REPO_ROOT / "protocol" / "v1"
PYTHON_OUT = REPO_ROOT / "src" / "sim_mirror" / "protocol" / "_generated.py"
TYPESCRIPT_OUT = REPO_ROOT / "viewer" / "src" / "protocol.generated.ts"
NOTICE = "Generated by scripts/gen_protocol.py from protocol/v1 -- do not edit."
SCALARS = {"string": "str", "integer": "int", "number": "float", "boolean": "bool", "null": "null"}
#: Any JSON object: one whose properties the protocol does not describe.
OPEN_OBJECT = "object"
T = TypeVar("T")


class SchemaError(Exception):
    """A schema this generator will not guess a type for."""


# -- type expressions ----------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class Scalar:
    name: str


@dataclass(frozen=True)
class LiteralValue:
    value: str | int


@dataclass(frozen=True)
class Ref:
    name: str


@dataclass(frozen=True)
class ListOf:
    item: TypeExpr


@dataclass(frozen=True)
class TupleOf:
    items: tuple[TypeExpr, ...]


@dataclass(frozen=True)
class UnionOf:
    members: tuple[TypeExpr, ...]


TypeExpr = Scalar | LiteralValue | Ref | ListOf | TupleOf | UnionOf


def refs_of(expr: TypeExpr) -> set[str]:
    """Every definition a type expression names."""
    if isinstance(expr, Ref):
        return {expr.name}
    if isinstance(expr, ListOf):
        return refs_of(expr.item)
    if isinstance(expr, (TupleOf, UnionOf)):
        parts = expr.items if isinstance(expr, TupleOf) else expr.members
        return set().union(*(refs_of(part) for part in parts))
    return set()


# -- definitions ------------------------------------------------------------------------------------------------------


@dataclass
class EnumDef:
    name: str
    constant: str
    values: tuple[str, ...]
    description: str


@dataclass
class AliasDef:
    name: str
    expr: TypeExpr
    description: str


@dataclass
class FieldDef:
    name: str
    expr: TypeExpr
    description: str


@dataclass
class RecordDef:
    name: str
    base: str | None
    fields: list[FieldDef]
    description: str


@dataclass
class UnionDef:
    name: str
    members: tuple[str, ...]
    description: str


Definition = AliasDef | RecordDef | UnionDef


@dataclass
class Model:
    constants: list[tuple[str, int]] = field(default_factory=list)
    enums: list[EnumDef] = field(default_factory=list)
    #: Aliases, records and unions, in the order they were defined.
    definitions: list[Definition] = field(default_factory=list)

    def ordered(self) -> list[Definition]:
        """The definitions so each comes after what it needs at import time: an alias's parts, a record's base, a
        union's members. A record's fields are annotations, read lazily, so they need nothing before them."""
        by_name = {definition.name: definition for definition in self.definitions}

        def needs(definition: Definition) -> set[str]:
            if isinstance(definition, AliasDef):
                return refs_of(definition.expr)
            if isinstance(definition, RecordDef):
                return {definition.base} if definition.base else set()
            return set(definition.members)

        return topological(self.definitions, lambda item: [by_name[n] for n in sorted(needs(item)) if n in by_name])


def topological(items: Sequence[T], dependencies: Callable[[T], Iterable[T]]) -> list[T]:
    """`items` in their own order, except that each comes after its dependencies."""
    ordered: list[T] = []
    seen: set[int] = set()

    def visit(item: T) -> None:
        if id(item) in seen:
            return
        seen.add(id(item))
        for dependency in dependencies(item):
            visit(dependency)
        ordered.append(item)

    for item in items:
        visit(item)
    return ordered


def pascal(key: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in key.split("_"))


class Builder:
    """Reads the schemas into a `Model`."""

    def __init__(self, schemas: dict[str, dict[str, Any]]) -> None:
        self._schemas = schemas
        self._model = Model()
        self._defined: set[str] = set()
        self._named: set[str] = set()

    def build(self) -> Model:
        for schema in self._schemas.values():
            for name, definition in (schema.get("$defs") or {}).items():
                self._define(name, definition)
            if "title" in schema:
                self._define(schema["title"], schema)
        unknown = sorted(self._named - self._defined)
        if unknown:
            raise SchemaError(f"references to nothing defined: {', '.join(unknown)}")
        records = {d.name for d in self._model.definitions if isinstance(d, RecordDef)}
        for definition in self._model.definitions:
            if isinstance(definition, RecordDef) and definition.base and definition.base not in records:
                raise SchemaError(f"{definition.name} extends {definition.base}, which is not an object")
        return self._model

    def _define(self, name: str, schema: dict[str, Any]) -> None:
        if name in self._defined:
            raise SchemaError(f"{name} is defined twice")
        self._defined.add(name)
        description = str(schema.get("description", ""))
        if "enum" in schema:
            values = schema["enum"]
            if "x-constant" not in schema or not all(isinstance(value, str) for value in values):
                raise SchemaError(f"{name}: an enum definition lists strings and names its constant with x-constant")
            self._model.enums.append(EnumDef(name, schema["x-constant"], tuple(values), description))
        elif "allOf" in schema:
            parts = schema["allOf"]
            if len(parts) != 2 or "$ref" not in parts[0] or parts[1].get("type") != "object":
                raise SchemaError(f"{name}: allOf is one $ref and the object that extends it")
            base = self._ref_name(parts[0]["$ref"])
            self._model.definitions.append(RecordDef(name, base, self._fields(name, parts[1]), description))
        elif "oneOf" in schema or "anyOf" in schema:
            members = schema.get("oneOf") or schema.get("anyOf") or []
            if not all("$ref" in member for member in members):
                raise SchemaError(f"{name}: a union definition lists only $refs")
            names = tuple(self._ref_name(member["$ref"]) for member in members)
            self._model.definitions.append(UnionDef(name, names, description))
        elif schema.get("type") == "object":
            self._model.definitions.append(RecordDef(name, None, self._fields(name, schema), description))
        else:
            self._model.definitions.append(AliasDef(name, self._expr(name, schema), description))

    def _fields(self, owner: str, schema: dict[str, Any]) -> list[FieldDef]:
        properties: dict[str, Any] = schema.get("properties") or {}
        optional = sorted(set(properties) - set(schema.get("required") or []))
        if optional:
            raise SchemaError(f"{owner}: every property is required (make it nullable instead): {', '.join(optional)}")
        return [
            FieldDef(key, self._expr(owner + pascal(key), value), str(value.get("description", "")))
            for key, value in properties.items()
        ]

    def _expr(self, context: str, schema: dict[str, Any]) -> TypeExpr:
        if "$ref" in schema:
            return Ref(self._ref_name(schema["$ref"]))
        if "const" in schema:
            return LiteralValue(schema["const"])
        if "enum" in schema:
            return UnionOf(tuple(LiteralValue(value) for value in schema["enum"]))
        if "oneOf" in schema or "anyOf" in schema:
            members = schema.get("oneOf") or schema.get("anyOf") or []
            return UnionOf(tuple(self._expr(context, member) for member in members))
        kind = schema.get("type")
        if isinstance(kind, list):
            return UnionOf(tuple(self._expr(context, {**schema, "type": one}) for one in kind))
        if kind in SCALARS:
            return Scalar(SCALARS[kind])
        if kind == "array" and "prefixItems" in schema:
            return TupleOf(tuple(self._expr(context, item) for item in schema["prefixItems"]))
        if kind == "array" and isinstance(schema.get("items"), dict):
            return ListOf(self._expr(context, schema["items"]))
        if kind == "object" and schema.get("additionalProperties") is True and "properties" not in schema:
            return Scalar(OPEN_OBJECT)
        if kind == "object":
            self._define(context, schema)
            return Ref(context)
        raise SchemaError(f"{context}: no type can be generated for {json.dumps(schema)[:100]}")

    def _ref_name(self, ref: str) -> str:
        file, _, pointer = ref.partition("#")
        prefix = "/$defs/"
        if not pointer.startswith(prefix) or (file and file not in self._schemas):
            raise SchemaError(f"cannot follow the reference {ref}: it names a $defs entry of a file in the folder")
        name = pointer[len(prefix) :]
        self._named.add(name)
        return name


# -- rendering --------------------------------------------------------------------------------------------------------


def _flatten(expr: TypeExpr) -> list[TypeExpr]:
    if isinstance(expr, UnionOf):
        return [inner for member in expr.members for inner in _flatten(member)]
    return [expr]


def _nullable_last(members: list[TypeExpr]) -> list[TypeExpr]:
    return [m for m in members if m != Scalar("null")] + [m for m in members if m == Scalar("null")]


def python_type(expr: TypeExpr) -> str:
    if isinstance(expr, Scalar):
        return {"null": "None", OPEN_OBJECT: "dict[str, Any]"}.get(expr.name, expr.name)
    if isinstance(expr, LiteralValue):
        return f"Literal[{json.dumps(expr.value)}]"
    if isinstance(expr, Ref):
        return expr.name
    if isinstance(expr, ListOf):
        return f"list[{python_type(expr.item)}]"
    if isinstance(expr, TupleOf):
        return f"tuple[{', '.join(python_type(item) for item in expr.items)}]"
    members = _nullable_last(_flatten(expr))
    if all(isinstance(member, LiteralValue) for member in members):
        return f"Literal[{', '.join(json.dumps(m.value) for m in members if isinstance(m, LiteralValue))}]"
    return " | ".join(python_type(member) for member in members)


def typescript_type(expr: TypeExpr) -> str:
    if isinstance(expr, Scalar):
        names = {"str": "string", "int": "number", "float": "number", "bool": "boolean", "null": "null"}
        return names.get(expr.name, "Record<string, unknown>")
    if isinstance(expr, LiteralValue):
        return f"'{expr.value}'" if isinstance(expr.value, str) else str(expr.value)
    if isinstance(expr, Ref):
        return expr.name
    if isinstance(expr, ListOf):
        inner = typescript_type(expr.item)
        return f"({inner})[]" if isinstance(expr.item, UnionOf) else f"{inner}[]"
    if isinstance(expr, TupleOf):
        return f"[{', '.join(typescript_type(item) for item in expr.items)}]"
    return " | ".join(typescript_type(member) for member in _nullable_last(_flatten(expr)))


def _comment(text: str, prefix: str, width: int = 116) -> list[str]:
    return [f"{prefix}{line}" for line in textwrap.wrap(text, width - len(prefix))] if text else []


def render_python(model: Model, version: int) -> str:
    lines = [
        "# SPDX-License-Identifier: Apache-2.0",
        f'"""The screen socket protocol, version {version}: its constants and message types.',
        "",
        NOTICE,
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any, Final, Literal, TypedDict",
        "",
    ]
    lines += [f"{name}: Final = {value}" for name, value in model.constants]
    for enum in model.enums:
        lines += ["", "", *_comment(enum.description, "# ")]
        lines += [f"{enum.name} = Literal[", *(f'    "{value}",' for value in enum.values), "]"]
        lines += [f"{enum.constant}: tuple[{enum.name}, ...] = (", *(f'    "{value}",' for value in enum.values), ")"]
    for definition in model.ordered():
        lines += ["", ""]
        if isinstance(definition, RecordDef):
            lines.append(f"class {definition.name}({definition.base or 'TypedDict'}):")
            if definition.description:
                wrapped = textwrap.wrap(definition.description, 110)
                lines += [f'    """{wrapped[0]}', *(f"    {line}" for line in wrapped[1:]), '    """']
            for item in definition.fields:
                lines += [*_comment(item.description, "    #: "), f"    {item.name}: {python_type(item.expr)}"]
            if not definition.fields and not definition.description:
                lines.append("    pass")
        elif isinstance(definition, AliasDef):
            lines += [*_comment(definition.description, "#: "), f"{definition.name} = {python_type(definition.expr)}"]
        else:
            lines += [*_comment(definition.description, "#: "), f"{definition.name} = {' | '.join(definition.members)}"]
    return "\n".join(lines) + "\n"


def render_typescript(model: Model, version: int) -> str:
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        f"// The screen socket protocol, version {version}: its constants and message types.",
        f"// {NOTICE}",
        "",
    ]
    lines += [f"export const {name} = {value}" for name, value in model.constants]
    for enum in model.enums:
        lines += ["", *_comment(enum.description, "// ")]
        lines.append(f"export const {enum.constant} = [{', '.join(repr(value) for value in enum.values)}] as const")
        lines.append(f"export type {enum.name} = (typeof {enum.constant})[number]")
    for definition in model.ordered():
        lines.append("")
        lines += _comment(definition.description, "// ")
        if isinstance(definition, RecordDef):
            extends = f" extends {definition.base}" if definition.base else ""
            lines.append(f"export interface {definition.name}{extends} {{")
            for item in definition.fields:
                lines += [*_comment(item.description, "  // "), f"  {item.name}: {typescript_type(item.expr)}"]
            lines.append("}")
        elif isinstance(definition, AliasDef):
            lines.append(f"export type {definition.name} = {typescript_type(definition.expr)}")
        else:
            lines.append(f"export type {definition.name} = {' | '.join(definition.members)}")
    return "\n".join(lines) + "\n"


# -- the folder -------------------------------------------------------------------------------------------------------


def _read(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise SchemaError(f"cannot read {path.name}: {exc}") from exc


def constants_of(constants: dict[str, Any], close_codes: dict[str, Any]) -> list[tuple[str, int]]:
    """The constants: every key of constants.json, then CLOSE_<NAME> for each close code."""
    found = [(key.upper(), value) for key, value in constants.items() if not key.startswith("$")]
    found += [
        (f"CLOSE_{key.upper()}", entry.get("code")) for key, entry in (close_codes.get("close_codes") or {}).items()
    ]
    wrong = [name for name, value in found if not isinstance(value, int) or isinstance(value, bool)]
    if wrong:
        raise SchemaError(f"constants are whole numbers: {', '.join(wrong)}")
    return found


def generate(schema_dir: Path) -> tuple[str, str]:
    """The Python and TypeScript files the folder's schemas and constants make."""
    schemas = {path.name: _read(path) for path in sorted(schema_dir.glob("*.schema.json"))}
    constants = _read(schema_dir / "constants.json")
    model = Builder(schemas).build()
    model.constants = constants_of(constants, _read(schema_dir / "close-codes.json"))
    version = constants.get("protocol_version")
    if not isinstance(version, int):
        raise SchemaError("constants.json names the protocol_version")
    return render_python(model, version), render_typescript(model, version)


def main(
    argv: list[str] | None = None,
    *,
    schema_dir: Path = SCHEMA_DIR,
    python_out: Path = PYTHON_OUT,
    typescript_out: Path = TYPESCRIPT_OUT,
) -> int:
    parser = argparse.ArgumentParser(description="Generate the protocol's Python and TypeScript types.")
    parser.add_argument("--check", action="store_true", help="exit 1 if a generated file is stale, writing nothing")
    args = parser.parse_args(argv)
    try:
        python, typescript = generate(schema_dir)
    except SchemaError as exc:
        print(f"protocol: {exc}", file=sys.stderr)
        return 2
    outputs = {python_out: python, typescript_out: typescript}
    if args.check:
        stale = [
            path for path, text in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        for path in stale:
            print(f"stale: {path} -- run `make generate`", file=sys.stderr)
        return 1 if stale else 0
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
